Added the small batch on the gdplib
SECQUOIA/gdplib pull request #10
Opened 2023-11-13 15:38 UTC by AlbertLee125

Added the gdp_small_batch.py on the gdp library.

2023-11-13 19:25 UTC, ZedongPeng requested changes
Good and well-structured PR.

2023-11-13 19:25 UTC, ZedongPeng commented on gdplib/small_batch/gdp_small_batch.py
> +            # Uncomment the following lines to setup IIS computation of BARON through option file
I think it is better for us to create an option to control if we want to set up the IIS computation.

2023-11-13 19:25 UTC, ZedongPeng commented on gdplib/small_batch/gdp_small_batch.py
> +    if not (os.path.exists(gams_path)):
Why do we need to check the `gamsfiles` here?

2023-11-13 19:25 UTC, ZedongPeng commented on gdplib/small_batch/gdp_small_batch.py
> +    """
If I understand correctly, this function aims to fix the disjunctions according to the provided variables and return the fixed model. We can come up with a better name for this function.

2023-11-13 19:25 UTC, ZedongPeng commented on gdplib/small_batch/gdp_small_batch.py
> +    # print('Y_not_exists[2, mixer] = ', newmodel.Y_not_exists[2, 'mixer'].indicator_var.value)
If these lines are only used for debugging, we can remove them.

2023-11-16 00:12 UTC, bernalde commented
I will only want us to work on this PR once all the other examples from GDPLib are updated to the latest version of Pyomo.

2024-04-17 01:55 UTC, bernalde requested changes
Since this is the first PR with our own newly contributed models, we need to be way more strict with the formatting. Debugging comments are no longer allowed. Only functions relevant to the model should be included (not the solution method). THe example itself is not the one found in Kocis and Grossmann, it is a simplification made for the LDSDA paper, so update the references.

2024-04-17 01:55 UTC, bernalde commented on gdplib/small_batch/gdp_small_batch.py
> +    - Kocis, G. R.; Grossmann, I. E. Global Optimization of Nonconvex Mixed-Integer Nonlinear Programming (MINLP) Problems in Process Synthesis. Ind. Eng. Chem. Res. 1988, 27 (8), 1407–1421.
DOI missing

2024-04-17 01:55 UTC, bernalde commented on gdplib/small_batch/gdp_small_batch.py
> +    References:
DOI

2024-04-17 01:55 UTC, bernalde commented on gdplib/small_batch/gdp_small_batch.py
> +    """
I agree with Zedong. This should work not only for the LDSDA but in general. Call it fix disjunctions. ALso, do we really need this now that there is the new implementation of LDSDA? @ZedongPeng

2024-04-17 01:55 UTC, bernalde commented on gdplib/small_batch/gdp_small_batch.py
> +                # m.Y_exists[k, j].indicator_var.fix(
These comments can go

2024-04-17 01:55 UTC, bernalde commented on gdplib/small_batch/gdp_small_batch.py
> +    if not (os.path.exists(gams_path)):
This function altogether is no longer needed. This was for the older implementation of LDSDA. Please remove it

2024-04-17 01:55 UTC, bernalde commented on gdplib/small_batch/gdp_small_batch.py
> +    # print('Y_not_exists[2, mixer] = ', newmodel.Y_not_exists[2, 'mixer'].indicator_var.value)
I agree, we need to clean this up

2024-05-21 18:08 UTC, AlbertLee125 commented on gdplib/small_batch/gdp_small_batch.py
> +    References:
DOI added and added the LD-SDA paper.

2024-05-21 18:08 UTC, AlbertLee125 commented on gdplib/small_batch/gdp_small_batch.py
> +    - Kocis, G. R.; Grossmann, I. E. Global Optimization of Nonconvex Mixed-Integer Nonlinear Programming (MINLP) Problems in Process Synthesis. Ind. Eng. Chem. Res. 1988, 27 (8), 1407–1421.
DOI added and added the LD-SDA paper.

2024-05-21 18:09 UTC, AlbertLee125 commented on gdplib/small_batch/gdp_small_batch.py
> +    if not (os.path.exists(gams_path)):
I will remove this.

2024-05-21 18:10 UTC, AlbertLee125 commented on gdplib/small_batch/gdp_small_batch.py
> +            # Uncomment the following lines to setup IIS computation of BARON through option file
This part will be removed.

2024-05-21 18:11 UTC, AlbertLee125 commented on gdplib/small_batch/gdp_small_batch.py
> +                # m.Y_exists[k, j].indicator_var.fix(
Comments removed.

2024-05-21 18:12 UTC, AlbertLee125 commented on gdplib/small_batch/gdp_small_batch.py
> +    # print('Y_not_exists[2, mixer] = ', newmodel.Y_not_exists[2, 'mixer'].indicator_var.value)
cleaned up the external ref test.

2024-05-21 18:26 UTC, AlbertLee125 commented on gdplib/small_batch/gdp_small_batch.py
> +    """
Zedong's new LDSDA does not require these anymore. Therefore, I just removed it since we need the model.

2024-05-21 20:24 UTC, AlbertLee125 reviewed
I renewed the documentation of the small_batch.py and fixed it from Google format to Numpy format.

2024-05-21 20:35 UTC, bernalde approved these changes
This looks good, @ZedongPeng if this code already runs with your LDSDA implementation, feel free to merge

2024-07-30 21:32 UTC, bernalde commented
Replace gam by gamma as it is the ration of Cp and Cv

2024-08-16 20:01 UTC, AlbertLee125 commented
The spelling check is failing because of the hda files. Besides the spelling check, there are no issues with the gdp_small_batch.py and I strongly believe this is ready to be merged. And I am not sure whether we have to discuss for the format of HDA files, There are two gammas one is the gamma for the ratio of the Cv and Cp the other is the decision variables related to the absorption process.

2024-08-17 00:31 UTC, bernalde requested changes
There is a typo is my last name in the references and the master branch needs to be merged before the tests will pass.

2024-08-17 00:31 UTC, bernalde commented on gdplib/small_batch/README.md
> +[2] Ovalle, D., Liñán, D. A., Lee, A., Gómez, J. M., Ricardez-Sandoval, L., Grossmann, I. E., & Neira, D. E. B. (2024). Logic-Based Discrete-Steepest Descent: A Solution Method for Process Synthesis
My last name to be cited is Bernal Neira, not Neira

2024-08-17 00:31 UTC, bernalde commented on gdplib/small_batch/gdp_small_batch.py
>  [2] Ovalle, D., Liñán, D. A., Lee, A., Gómez, J. M., Ricardez-Sandoval, L., Grossmann, I. E., & Neira, D. E. B. (2024). Logic-Based Discrete-Steepest Descent: A Solution Method for Process Synthesis
See previous comment regarding last name. Fix elsewhere.

2024-08-19 16:17 UTC, AlbertLee125 commented on gdplib/small_batch/gdp_small_batch.py
>  [2] Ovalle, D., Liñán, D. A., Lee, A., Gómez, J. M., Ricardez-Sandoval, L., Grossmann, I. E., & Neira, D. E. B. (2024). Logic-Based Discrete-Steepest Descent: A Solution Method for Process Synthesis
Replaced Neira, D. E. B. into Bernal Neira, D. E.

2024-08-19 20:33 UTC, bernalde approved these changes

2024-08-19 20:34 UTC, ZedongPeng approved these changes

2024-08-19 20:34 UTC, merged