Add jobshop scheduling model and small concrete model documentation
SECQUOIA/gdplib pull request #11
Opened 2023-12-22 02:36 UTC by AlbertLee125

2024-01-10 16:58 UTC, ZedongPeng requested changes
Well done.

2024-01-10 16:58 UTC, ZedongPeng commented on gdplib/pyomo_examples/jobshop.py
>      def t_bounds(model, I):
Try to use the black format.

2024-01-10 16:58 UTC, ZedongPeng commented on gdplib/pyomo_examples/jobshop.py
>      def t_bounds(model, I):
I am a little confused as to why `I` is not used in this function.

2024-01-10 16:58 UTC, ZedongPeng commented on gdplib/pyomo_examples/jobshop.py
> +            bool: True if the makespan is greater than the sum of the start time of every job and that job's total duration.
The function returns an expression instead of a Bool.

2024-01-10 16:58 UTC, ZedongPeng commented on gdplib/pyomo_examples/jobshop.py
> +            J J (int): stage index
Remove the redundant `J`.

2024-01-10 16:58 UTC, ZedongPeng commented on gdplib/pyomo_examples/jobshop.py
>          return [model.NoClash[I,K,J,IthenK] for IthenK in model.I_BEFORE_K]
Use black format.

2024-01-19 18:28 UTC, AlbertLee125 commented on gdplib/pyomo_examples/jobshop.py
> +            J J (int): stage index
J removed.

2024-01-19 19:12 UTC, AlbertLee125 commented on gdplib/pyomo_examples/jobshop.py
>          return [model.NoClash[I,K,J,IthenK] for IthenK in model.I_BEFORE_K]
Black Format applied

2024-01-19 19:15 UTC, AlbertLee125 commented on gdplib/pyomo_examples/jobshop.py
> +            bool: True if the makespan is greater than the sum of the start time of every job and that job's total duration.
Fixed it into expression.

2024-01-19 19:36 UTC, AlbertLee125 commented on gdplib/pyomo_examples/jobshop.py
>      def t_bounds(model, I):
This is the time bounds of the each batch with different stages. According to the Reference Literature, t_bounds represent the boundary for the starting time t_i. However, since they get the upper bound from tau which is represented as i × j matrix instead of using the model.JOBS. Though removing the unused index seems a good idea, I think remaining the 'I' to implie where the bounds came from.

2024-01-19 19:43 UTC, AlbertLee125 commented
I adjusted the code based on your feedback. However, I just leave the time-bound function to leave the I index, though 'I' is not used. The time-bound is set by the tau which is a matrix. Leaving 'I' would help the reviewer to understand what the time-bounds are for.

2024-01-20 01:13 UTC, bernalde requested changes
Apply the changes also mentioned in the other PR here. Have you run this? Does it solve? In general, I want you to also record the solution time for each instance in Dantzig using the diferent reformulations as in the LD-DSDA paper and report them into the README of each file. I want to know how each instance solves.

2024-01-20 01:13 UTC, bernalde commented on gdplib/pyomo_examples/jobshop.py
> +        """_summary_
_summary_?

2024-01-20 01:13 UTC, bernalde commented on gdplib/pyomo_examples/jobshop.py
> +            expression: True if the makespan is greater than the sum of the start time of every job and that job's total duration.
THe return is not called expression, its type is an expression

2024-03-01 17:16 UTC, tristantc commented on gdplib/pyomo_examples/jobshop.py
> +            bool: True if the makespan is greater than the sum of the start time of every job and that job's total duration.
I leave it as expression.

2024-03-14 14:29 UTC, ZedongPeng commented on gdplib/pyomo_examples/jobshop.py
> +            expression: True if the makespan is greater than the sum of the start time of every job and that job's total duration.
The documentation is still wrong. This function returns an expression, not a boolean.

2024-03-27 19:29 UTC, tristantc commented on gdplib/pyomo_examples/jobshop.py
> +        """_summary_
Added function description of the _feas function.

2024-03-27 21:13 UTC, AlbertLee125 reviewed
The Summary parts is fixed with New documentation and Bulil Model function is also documented.  I think it is ready to be merged.

2024-03-28 02:05 UTC, bernalde requested changes
A couple of requested changes. The most pressing one is getting the function formatting right.
Details are here (although I recommend reading the whole article once at least) https://realpython.com/documenting-python-code/#numpyscipy-docstrings-example
Also follow Pyomo's contributing guide https://pyomo.readthedocs.io/en/latest/contribution_guide.html in running black and the spellchecker.

2024-03-28 02:05 UTC, bernalde commented on gdplib/pyomo_examples/jobshop.py
Does the header of this file correspond to the one in Pyomo? If not, please correct.

2024-03-28 02:05 UTC, bernalde commented on gdplib/pyomo_examples/jobshop.py
> +# Raman & Grossmann, Modelling and computational techniques for logic based integer programming, Computers and Chemical Engineering 18, 7, p.563-578, 1994.
Missing doi

2024-03-28 02:05 UTC, bernalde commented on gdplib/pyomo_examples/jobshop.py
>  # Aldo Vecchietti, LogMIP User's Manual, http://www.logmip.ceride.gov.ar/, 2007
Missing doi

2024-03-28 02:05 UTC, bernalde commented on gdplib/pyomo_examples/jobshop.py
> +    Args: None
Is this Numpy formatting? If not, please update it across the code

2024-04-01 22:56 UTC, tristantc commented on gdplib/pyomo_examples/jobshop.py
Header now reflects pyomo's latest version

2024-04-01 23:07 UTC, tristantc reviewed
Citation doi now present in jobshop.py

2024-04-01 23:07 UTC, tristantc commented on gdplib/pyomo_examples/jobshop.py
> +# Raman & Grossmann, Modelling and computational techniques for logic based integer programming, Computers and Chemical Engineering 18, 7, p.563-578, 1994.
Citation doi now present in jobshop.py

2024-04-02 03:09 UTC, bernalde requested changes
Almost there.
We need numpy documentation.
Details here https://numpydoc.readthedocs.io/en/latest/format.html (have it automatically set up in VSCode https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring

2024-04-02 03:09 UTC, bernalde commented on gdplib/pyomo_examples/jobshop.py
> +    Args: None
By this I meant the formatting version where you have:
```
Parameters
----------
x : type
    Description of parameter `x`.
y
    Description of parameter `y` (with type not specified).

Returns
-------
err_code : int
    Non-zero value indicates error code, or zero on success.
err_msg : str or None
    Human readable error message, or None on success.
```
See details here https://numpydoc.readthedocs.io/en/latest/format.html
Modify your autoformatter

2024-04-04 19:58 UTC, bernalde approved these changes
Ready to be merged!

2024-04-04 22:29 UTC, ZedongPeng approved these changes

2024-04-04 22:29 UTC, merged

2024-04-12 01:29 UTC, ZedongPeng reviewed
Hi @AlbertLee125 . Sorry for the late comments. Resolving my comments should be easy.

2024-04-12 01:29 UTC, ZedongPeng commented on gdplib/pyomo_examples/jobshop.py
>      def _disj(model, I, K, J):
`_disj` tells nothing. Try a more detailed name.

2024-04-12 01:29 UTC, ZedongPeng commented on gdplib/pyomo_examples/jobshop.py
>      def _feas(model, I):
Try a better name than `_feas`.