Add documentation on the disease_model.py
SECQUOIA/gdplib pull request #12
Opened 2023-12-22 21:21 UTC by AlbertLee125

2024-01-10 17:09 UTC, ZedongPeng requested changes
Well done. Just a few small comments to address before merging.

2024-01-10 17:09 UTC, ZedongPeng commented on gdplib/pyomo_examples/disease_model.py
> +        boundary greater than zero
Boundary (Upper case).

2024-01-10 17:09 UTC, ZedongPeng commented on gdplib/pyomo_examples/disease_model.py
> +    # model.logI = Var(model.S_meas, bounds=_gt_zero, doc='log of estimated cases')
Could we remove the commented code?

2024-01-10 17:09 UTC, ZedongPeng commented on gdplib/pyomo_examples/disease_model.py
>          return (0.0, expr)
What is `0.0` used for here?

2024-01-10 17:09 UTC, ZedongPeng commented on gdplib/pyomo_examples/disease_model.py
>      def _beta_bounds(m):
`_beta_bounds` function is not used. Can we just remove this?

2024-01-10 17:09 UTC, ZedongPeng commented on gdplib/pyomo_examples/disease_model.py
> +        _type_: _description_
We need to update this line.

2024-01-10 17:46 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
> +    # model.logI = Var(model.S_meas, bounds=_gt_zero, doc='log of estimated cases')
Make sure to include the documentation in the commented code in the variable definition

2024-01-19 19:45 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
> +        boundary greater than zero
Upper case fixed.

2024-01-19 21:16 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
>          return (0.0, expr)
The model enforces that the actual dynamics (captured in the expression expr) follow the specified dynamics of the SIR model for each biweekly period by setting the expression equal to zero.
This is the constraint of the differential function discretized.

2024-01-19 21:20 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
> +    # model.logI = Var(model.S_meas, bounds=_gt_zero, doc='log of estimated cases')
Some of the commented code set the logged variable greater than zero to avoid numerical instabilities. There is also binary variables which are not used. But I added the comment after the build_model function so that I can explain how the bigM reformulation is applied.

2024-01-19 21:20 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
>      def _beta_bounds(m):
I think we need to remain this.

2024-01-19 21:24 UTC, AlbertLee125 commented
I updated the code with more explanation of the code and detail comments on the code. Please review this later.

2024-01-20 01:08 UTC, bernalde requested changes
Changes need to be made for this. I would suggest running black on this code as well

2024-01-20 01:08 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
> +    # # log of transmission parameter beta
Why double comment?

2024-01-20 01:08 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
> +    # # log of transmission parameter beta
In fact, let's remove this comment as that information is already available in the variable documentation (no need to double comment)

2024-01-20 01:08 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
>      model.logbeta_low = Var(bounds=(0.0001,5))
Here is where the documentation should go

2024-01-20 01:08 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
>      meanS = 8.65e5
Units?

2024-01-20 01:08 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
>          return (0.0, expr)
Please comment this in the documentation

2024-01-20 01:08 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
>  """
Let's use the chance to remove this commenting block

2024-01-20 01:08 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
>  """
As in remove """

2024-01-23 15:28 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
>      meanS = 8.65e5
Number of Humans(Population)

2024-01-23 15:30 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
> +    # # log of transmission parameter beta
Double comments are removed.

2024-01-23 15:33 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
>  """
Removed the blocked Comments.

2024-01-23 15:39 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
>      model.logbeta_low = Var(bounds=(0.0001,5))
Added the documentation after removing a block of comment. Add the documentation where the binary variables and the disjuncts are.

2024-01-23 15:41 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
> +        _type_: _description_
Added the documenatation to describe Args and Return.

2024-01-24 01:19 UTC, bernalde requested changes
More changes. Don't forget to run black on the code

2024-01-24 01:19 UTC, bernalde commented on gdplib/pyomo_examples/READMEdisease.md
> +Total time = 2.08 seconds
With which reformulation? I would like to see how logic-based methods behave with this. All in a table form (Solution method, subsolver, time, solution)

2024-01-24 01:19 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
> +    """
We don't add inline comments with """. We reserve that for function documentation

2024-01-24 01:19 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
> +    # mean susceptibles (Number of Population)
Number of population? Do you mean the number of individuals? Is it integer?

2024-01-24 01:19 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
>      meanS = 8.65e5
Please comment it afterwards `meanS = 8.65e5 # Number of humans`

2024-01-24 01:19 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
> +    # log of measured population (Number of Population(log scale))
Then it is log(Number of humans) (is it log base 2 or 10?)

2024-03-27 18:57 UTC, ZedongPeng commented
For the `docstring`, I would suggest using the Numpy format. We can set it in the Python docstring extension in VSCode. Just to keep consistent with `Pyomo`.

2024-04-04 22:16 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
> +    # log of measured population (Number of Population(log scale))
Added the documentation of the log scale and also mentioned about common logarithm

2024-04-04 22:21 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
>          return (0.0, expr)
Added on the Notes.

2024-04-04 22:21 UTC, AlbertLee125 commented on gdplib/pyomo_examples/READMEdisease.md
> +Total time = 2.08 seconds
I think this one does not need to be added right now. I will only manage on the documentation from now on.

2024-04-04 22:27 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
>      meanS = 8.65e5
Fixed the comment.

2024-04-04 22:35 UTC, AlbertLee125 reviewed
For the disease model, I fixed it into Numpy Format and For the READMEdisease.md I think I need to remove it, since I only focused on the documentation of the code itself

2024-04-04 22:39 UTC, bernalde requested changes
Black seemed to have messed up with some parameters. Please revert them.
Also, the markdown either fix them or remove it from the PR.

2024-04-04 22:39 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
> +    pop = [
Why is this separated? Is this the black formatting?

2024-04-04 22:39 UTC, bernalde commented on gdplib/pyomo_examples/disease_model.py
> +# # disjuncts
Why is this second disjunct commented? At least add a comment trying to explain that

2024-04-04 22:39 UTC, bernalde commented on gdplib/pyomo_examples/READMEdisease.md
> +Total time = 2.08 seconds
I strongly disagree with you.
If this is not to be included, then do not include it in the PR.

2024-04-05 14:52 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
> +    pop = [
I reverted the change of the black formatting on the data.

2024-04-05 15:05 UTC, AlbertLee125 commented on gdplib/pyomo_examples/disease_model.py
> +# # disjuncts
The commented code was commented at the first place with """ """.
The commented code sets up explicit high and low beta constraints for the SIR model using a big-M reformulation, bypassing Pyomo's built-in disjunctive programming tools.
I just added the documenation explaining about the commented code.

2024-04-05 15:07 UTC, AlbertLee125 commented on gdplib/pyomo_examples/READMEdisease.md
> +Total time = 2.08 seconds
Then I would like to delete the READMEdisease.md file and Then build another branch for the benchmarking.

2024-04-17 01:56 UTC, bernalde approved these changes

2024-04-17 02:13 UTC, ZedongPeng approved these changes

2024-04-17 02:13 UTC, merged