Pyomo_med_term_purchasing
SECQUOIA/gdplib pull request #13
Opened 2024-04-11 18:40 UTC by AlbertLee125

I added the documentation of the medium term purchasing problem.

2024-04-12 01:34 UTC, ZedongPeng requested changes
Good Job. The comments should be easy to resolve.

2024-04-12 01:34 UTC, ZedongPeng commented on gdplib/pyomo_examples/med_term_purchasing.py
> +        _description_
Replace the `_description_` with detailed description.
Maybe we could check if the `RuntimeErrors`are necessary. If not, we can remove them.

2024-04-12 01:34 UTC, ZedongPeng commented on gdplib/pyomo_examples/med_term_purchasing.py
>      ## UPPER BOUNDS HARDCODED INTO GAMS MODEL
Can we remove this line?

2024-04-12 01:34 UTC, ZedongPeng commented on gdplib/pyomo_examples/med_term_purchasing.py
>      model = AbstractModel()
Why do we prefer `AbstractModel` instead of `ConcreteModel` here?

2024-04-12 01:34 UTC, ZedongPeng commented on gdplib/pyomo_examples/med_term_purchasing.py
>  # most notably the process structure itself and the mass balance information.
In line 16, the current link directs to the model list.
it would be better if we update the link to the following, which directs to the **Medium-Term Purchasing Contracts** problem.
https://www.minlp.org/library/problem/index.php?i=129&lib=GDP

2024-04-12 01:34 UTC, ZedongPeng commented on gdplib/pyomo_examples/med_term_purchasing.py
>  # most notably the process structure itself and the mass balance information.
Modify the other files if this applies.

2024-04-12 01:34 UTC, ZedongPeng commented on gdplib/pyomo_examples/med_term_purchasing.py
>      def FD_contract(model, j, t):
In other files like `jobshop`, the functions are defined as internal functions, which begin with `_`. We'd unify them.

2024-04-16 22:28 UTC, tristantc commented on gdplib/pyomo_examples/med_term_purchasing.py
>  # most notably the process structure itself and the mass balance information.
Updated link available now.

2024-04-17 01:42 UTC, bernalde commented on gdplib/pyomo_examples/med_term_purchasing.py
>      model = AbstractModel()
We will not change that in this implementation as long as it is based on the one in the Pyomo repo. @AlbertLee125 confirm this, please

2024-04-17 01:43 UTC, bernalde commented on gdplib/pyomo_examples/med_term_purchasing.py
>      def FD_contract(model, j, t):
This is a fair observation, but we will not go into modifying the code now as it would deviate from the implementation in Pyomo.
Bring this issue up in the next Pyomo developers meeting, if there is a preferred style guide and then we will abide to it.

2024-04-17 01:47 UTC, bernalde requested changes
It seems that black has not yet been run in this file and that some comments are still open. Once you address them, this is ready to merge

2024-04-17 01:47 UTC, bernalde commented on gdplib/pyomo_examples/med_term_purchasing.py
> +        _description_
@AlbertLee125 @tristantc this is missing

2024-04-17 01:47 UTC, bernalde commented on gdplib/pyomo_examples/med_term_purchasing.py
> +    """
DOIs missing and the description of the runtime error is incomplete

2024-04-17 01:53 UTC, tristantc commented on gdplib/pyomo_examples/med_term_purchasing.py
> +    """
The current references are not relevant to the Medium-term Purchasing Contracts problem.
Review and update to:
Park, M., Park, S., Mele, F. D., & Grossmann, I. E. (2006). Modeling of purchase and sales contracts in supply chain optimization. Industrial and Engineering Chemistry Research, 45(14), 5013–5026. https://doi.org/10.1021/ie0513144

2024-04-19 22:12 UTC, tristantc commented on gdplib/pyomo_examples/med_term_purchasing.py
> +    """
Updated references following APA guidelines

2024-04-19 22:28 UTC, tristantc commented on gdplib/pyomo_examples/med_term_purchasing.py
> +        _description_
Is not present in the pyomo repository [examples/gdp/medTermPurchasing_Literal.py] (https://github.com/Pyomo/pyomo/blob/fa5d0b6f44a8b96f7e644e496e8ac9c9a517d7ce/examples/gdp/medTermPurchasing_Literal.py).

2024-04-23 15:19 UTC, AlbertLee125 commented on gdplib/pyomo_examples/med_term_purchasing.py
>      model = AbstractModel()
It is the abstract model then there is an another function that converts the abstract model into concrete model by importing the .dat file.

2024-04-23 15:19 UTC, AlbertLee125 commented on gdplib/pyomo_examples/med_term_purchasing.py
>      def FD_contract(model, j, t):
I will change it later for the future work.

2024-04-23 15:20 UTC, AlbertLee125 commented on gdplib/pyomo_examples/med_term_purchasing.py
>      ## UPPER BOUNDS HARDCODED INTO GAMS MODEL
I think I would leave this at it is.

2024-04-23 15:20 UTC, AlbertLee125 commented on gdplib/pyomo_examples/med_term_purchasing.py
> +        _description_
Removed the Runtime.

2024-04-23 15:53 UTC, AlbertLee125 commented on gdplib/pyomo_examples/med_term_purchasing.py
> +    """
Removed the runtime error. And I added the Carolina Reference. For Vecchietti references, I added it becaues He mentiones solving the problem when talking about the logmip case studies. And I think I need to add the Park's references as well. I added their reference.

2024-04-23 16:00 UTC, AlbertLee125 commented on gdplib/pyomo_examples/med_term_purchasing.py
> +    """
I was not able to find the FOCAPD reference DOI

2024-04-23 16:20 UTC, tristantc commented on gdplib/pyomo_examples/med_term_purchasing.py
> +    """
@AlbertLee125 I have already made the updates to the references.

2024-04-23 16:24 UTC, AlbertLee125 reviewed
> @AlbertLee125 I have already made the updates to the references. 

I shall not add Park's reference?

2024-04-23 16:28 UTC, tristantc commented
> > @AlbertLee125 I have already made the updates to the references.
> 
> I shall not add Park's reference?

My changes ([d153238](https://github.com/SECQUOIA/gdplib/pull/13/commits/d153238eac297259051ce79379093a9ca94ecdcf)) are currently in conflict with yours ([10e91a4](https://github.com/SECQUOIA/gdplib/pull/13/commits/10e91a456866aaf34d93b27fb00b0d5107129e4e)).

2024-04-25 16:27 UTC, AlbertLee125 reviewed
I changed the reference style back to Carolina's and black formatted again. Can you chek it?

2024-04-25 16:27 UTC, AlbertLee125 commented on gdplib/pyomo_examples/med_term_purchasing.py
> +    """
I changed the reference back with Carolina

2024-04-25 16:34 UTC, ZedongPeng approved these changes

2024-05-06 19:00 UTC, AlbertLee125 reviewed
I removed the unnecesary references and adjust it to Carolina's reference suggestion.

2024-05-06 19:01 UTC, ZedongPeng approved these changes

2024-05-06 20:16 UTC, merged