Logical-spectralog
SECQUOIA/gdplib pull request #15
Opened 2024-04-20 00:58 UTC by AlbertLee125

Added the documentation of the Logical Spectralog. Added the original sources of the references.
And explain where the String IO refer to.

2024-04-22 13:12 UTC, ZedongPeng approved these changes

2024-05-03 01:18 UTC, bernalde requested changes

2024-05-03 01:18 UTC, bernalde commented on gdplib/logical/spectralog.py
>  from pyomo.environ import *
Are any of the commented lines above still relevant? Please modify accordingly

2024-05-03 01:18 UTC, bernalde commented on gdplib/logical/spectralog.py
> +        doc='Objective to maximize spectroscopic agreement and encourage compound presence.',
This description is off. Compare it to the comment below

2024-05-09 03:51 UTC, AlbertLee125 commented on gdplib/logical/spectralog.py
> +        doc='Objective to maximize spectroscopic agreement and encourage compound presence.',
I changed the doc to make better alignment with the comment below.

2024-05-09 04:03 UTC, AlbertLee125 commented on gdplib/logical/spectralog.py
>  from pyomo.environ import *
Modified the commented line as the header.

2024-05-09 14:47 UTC, bernalde approved these changes

2024-05-09 14:47 UTC, merged