Syngas Documentation
SECQUOIA/gdplib pull request #16
Opened 2024-04-22 22:42 UTC by AlbertLee125

I have documented the Syngas case and added the original references of the given problem.

2024-04-24 03:36 UTC, bernalde requested changes
There are a number of missing spaces before parenthesis and some comments to be addressed.

2024-04-24 03:36 UTC, bernalde commented on gdplib/syngas/syngas_adapted.py
> +    """_summary_
Missing summary

2024-04-24 03:36 UTC, bernalde commented on gdplib/syngas/syngas_adapted.py
> +                / 8000
Add a comment that this referes to 8000 hr/ year

2024-04-24 03:36 UTC, bernalde commented on gdplib/syngas/syngas_adapted.py
> +    # PSA(pressure swing adsorption)
Add space before (

2024-04-24 03:36 UTC, bernalde commented on gdplib/syngas/syngas_adapted.py
> +            Ensures the sum of outflow and purge equals the inflow for the mixer(ms4) across all species.
Add space before (

2024-04-24 03:36 UTC, bernalde commented on gdplib/syngas/syngas_adapted.py
> +        Limits the purge flow of each species to no more than 1% of its inflow to the mixer(ms4).
Add space before (

2024-04-24 03:36 UTC, bernalde commented on gdplib/syngas/syngas_adapted.py
> +            Constrains the purge flow to a maximum of 1% of the respective species' inflow to the MS4, aiding in maintaining environmental and process control standards.
Are we using upper case (MS4) or lower case (ms4) for units? Standardize it

2024-04-24 03:52 UTC, AlbertLee125 commented on gdplib/syngas/syngas_adapted.py
> +    # PSA(pressure swing adsorption)
space added.

2024-04-24 04:00 UTC, AlbertLee125 commented on gdplib/syngas/syngas_adapted.py
> +            Ensures the sum of outflow and purge equals the inflow for the mixer(ms4) across all species.
Separated the space. And the ms and m both stands for the mixer. However, ms is a mixer/splitter unit and m is mixer itself. I will check the documentation

2024-04-24 04:03 UTC, AlbertLee125 commented on gdplib/syngas/syngas_adapted.py
> +            Constrains the purge flow to a maximum of 1% of the respective species' inflow to the MS4, aiding in maintaining environmental and process control standards.
I will unify as lower case.

2024-04-24 04:04 UTC, AlbertLee125 commented on gdplib/syngas/syngas_adapted.py
> +                / 8000
Added # [8000 hr/yr] for all existing 8 cases.

2024-04-24 04:14 UTC, AlbertLee125 commented on gdplib/syngas/syngas_adapted.py
> +    """_summary_
Added the documentation. Used the GenAI of Grammarly to fix the grammar error and enhance the Notes footage.

2024-05-08 13:47 UTC, ZedongPeng approved these changes

2024-05-09 14:50 UTC, bernalde approved these changes
Consider this approved from my side once the slashes are fixed.
Merging contingent on @ZedongPeng and @tristantc reviews

2024-05-09 14:50 UTC, bernalde commented on gdplib/syngas/syngas_adapted.py
> +        Limits the purge flow of each species to no more than 1% of its inflow to the mixer\splitter (ms4).
Wrong slash "/"

2024-05-09 14:50 UTC, bernalde commented on gdplib/syngas/syngas_adapted.py
> +            Enforces that the inflow of each species into splitter (s2) equals the outflow from splitter (s2) to the mixer\splitter (ms1).
Wrong slash

2024-05-12 15:47 UTC, AlbertLee125 commented on gdplib/syngas/syngas_adapted.py
> +            Enforces that the inflow of each species into splitter (s2) equals the outflow from splitter (s2) to the mixer\splitter (ms1).
slash fixed.

2024-05-12 15:47 UTC, AlbertLee125 commented on gdplib/syngas/syngas_adapted.py
> +        Limits the purge flow of each species to no more than 1% of its inflow to the mixer\splitter (ms4).
slash fixed

2024-05-12 20:45 UTC, merged