Update documentation for supply and demand constraints in biofuel model
SECQUOIA/gdplib pull request #17
Opened 2024-04-24 03:47 UTC by AlbertLee125

This pull request updates the documentation for the supply and demand constraints in the biofuel model. It includes setting up the parameters of the distance and the coordinates of the supermarket and site, as well as adding documentation on the parameter and references. Additionally, it adds documentation of the disjunct and the disjunctions.

2024-05-03 01:21 UTC, bernalde requested changes

2024-05-03 01:21 UTC, bernalde commented on gdplib/biofuel/model.py
from __future__ import division is not needed (it was required for Python 2)

2024-05-03 01:21 UTC, bernalde commented on gdplib/biofuel/model.py
>  import pandas as pd
Missing file header

2024-05-03 01:21 UTC, bernalde commented on gdplib/biofuel/model.py
> +    """_summary_
__sumary__?

2024-05-08 13:52 UTC, ZedongPeng commented on gdplib/biofuel/model.py
>      m.bigM = Suffix(direction=Suffix.LOCAL)
It might be better if we set the default `BigM =7000` here.

2024-05-09 01:51 UTC, AlbertLee125 commented on gdplib/biofuel/model.py
I removed the from future import division. Since the line is outdated.

2024-05-09 02:35 UTC, AlbertLee125 commented on gdplib/biofuel/model.py
> +    """_summary_
Added the description.

2024-05-09 03:04 UTC, AlbertLee125 commented on gdplib/biofuel/model.py
>      m.bigM = Suffix(direction=Suffix.LOCAL)
I added the name on the ConCreteModel.

2024-05-09 03:19 UTC, AlbertLee125 commented on gdplib/biofuel/model.py
>  import pandas as pd
Added the file header.

2024-05-09 03:20 UTC, AlbertLee125 commented on gdplib/biofuel/model.py
>      m.bigM = Suffix(direction=Suffix.LOCAL)
I use initialize to set default value as 7000.

2024-05-09 15:09 UTC, ZedongPeng approved these changes

2024-05-16 19:43 UTC, bernalde approved these changes

2024-05-16 19:43 UTC, merged