Refactor alphanumeric sorting functions and update documentation
SECQUOIA/gdplib pull request #19
Opened 2024-04-28 02:13 UTC by AlbertLee125

This pull request includes the following changes:

- Refactor alphanumeric sorting functions in util.py

- Add references on the model.py

- Document the parameters of the stranded gas models

- Update documentation on the disjunctions for exist of module type

2024-05-03 01:23 UTC, bernalde requested changes

2024-05-03 01:23 UTC, bernalde commented on gdplib/stranded_gas/model.py
Missing file header, remove from __future__import division

2024-05-08 13:45 UTC, ZedongPeng commented
I think this PR is ready to be merged after resolving the file header.

2024-05-09 14:52 UTC, bernalde approved these changes
Merging contingent on other reviews (@ZedongPeng and @tristantc )

2024-05-09 15:07 UTC, ZedongPeng approved these changes

2024-05-12 20:44 UTC, merged