Benchmark code with the result example of jobshop
SECQUOIA/gdplib pull request #21
Opened 2024-05-07 01:17 UTC by ZedongPeng

This is the first working version of the `benchmark` function. I also uploaded the result example of the `Jobshop` model.
Let's review it before submitting the full benchmark test.
@bernalde @AlbertLee125 @tristantc

2024-05-07 08:46 UTC, bernalde requested changes
Great start. Some small requirements. I would separate the part of putting everything in its own directory for a separate PR

2024-05-07 08:46 UTC, bernalde commented on gdplib/jobshop/benchmark_result/2024-05-06_21-01-21/gdp.bigm_scip.json
> +{"Problem": [{"Lower bound": -Infinity, "Upper bound": 11.0, "Number of objectives": 1, "Number of constraints": 0, "Number of variables": 10, "Sense": "unknown"}], "Solver": [{"Status": "ok", "Messa
Why is the sense unkown?
We also need more resolution in the time.

2024-05-07 08:46 UTC, bernalde commented on gdplib/jobshop/benchmark_result/2024-05-06_21-01-21/gdpopt.gloa_scip.json
> +{"Problem": [{"Name": "unknown", "Lower bound": 11.0, "Upper bound": 11.0, "Number of objectives": 1, "Number of constraints": 9, "Number of variables": 10, "Number of binary variables": 6, "Number o
We should keep the name of the problems and the GDPLib in the problem name

2024-05-07 08:46 UTC, bernalde commented on gdplib/jobshop/model_size_report.md
Can we generate a similar table for the benchmarking summary?

2024-05-07 08:46 UTC, bernalde commented on benchmark.py
> +    """Benchmark the model using the given strategy and subsolver.
More description, especially regarding the data output. Also include the return none statement.

2024-05-07 15:24 UTC, ZedongPeng commented on gdplib/jobshop/benchmark_result/2024-05-06_21-01-21/gdp.bigm_scip.json
> +{"Problem": [{"Lower bound": -Infinity, "Upper bound": 11.0, "Number of objectives": 1, "Number of constraints": 0, "Number of variables": 10, "Sense": "unknown"}], "Solver": [{"Status": "ok", "Messa
The unknown `sense` might be related to the`pyomo-scip` interface. I will submit an issue for this.
According to the log of `scip`, it seems that the time provided by `scip` has only two decimal places, which we cannot improve at this moment.

```
SCIP version 8.1.0 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: Soplex 6.0.4] [GitHash: 816db6b8a8]
Copyright (c) 2002-2023 Zuse Institute Berlin (ZIB)

External libraries: 
  Soplex 6.0.4         Linear Programming Solver developed at Zuse Institute Berlin (soplex.zib.de) [GitHash: 950b1658]
  CppAD 20180000.0     Algorithmic Differentiation of C++ algorithms developed by B. Bell (github.com/coin-or/CppAD)
  ZLIB 1.2.13          General purpose compression library by J. Gailly and M. Adler (zlib.net)
  GMP 6.3.0            GNU Multiple Precision Arithmetic Library developed by T. Granlund (gmplib.org)
  ZIMPL 3.5.3          Zuse Institute Mathematical Programming Language developed by T. Koch (zimpl.zib.de)
  AMPL/MP 4e2d45c4     AMPL .nl file reader library (github.com/ampl/mp)
  PaPILO 2.1.4         parallel presolve for integer and linear optimization (github.com/scipopt/papilo) [GitHash: ee0677c]
  bliss 0.77           Computing Graph Automorphism Groups by T. Junttila and P. Kaski (https://users.aalto.fi/~tjunttil/bliss/)
  Ipopt 3.14.12        Interior Point Optimizer developed by A. Waechter et.al. (github.com/coin-or/Ipopt)

reading user parameter file <scip.set>
===========================

limits/time = 600

read problem </var/folders/pj/1113b24j7b3083zbt19pjxqm0000gn/T/tmprbs4pc3k.pyomo.nl>
============

original problem has 10 variables (6 bin, 0 int, 0 impl, 4 cont) and 12 constraints

solve problem
=============

presolving:
(round 1, fast)       3 del vars, 3 del conss, 0 add conss, 1 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 0 clqs
(round 2, fast)       3 del vars, 3 del conss, 0 add conss, 2 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 0 clqs
   (0.0s) running MILP presolver
   (0.0s) MILP presolver found nothing
   (0.0s) probing cycle finished: starting next cycle
(round 3, exhaustive) 3 del vars, 3 del conss, 0 add conss, 3 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 12 impls, 0 clqs
   (0.0s) probing cycle finished: starting next cycle
   (0.0s) symmetry computation started: requiring (bin +, int -, cont +), (fixed: bin -, int +, cont -)
   (0.0s) no symmetry present (symcode time: 0.00)
presolving (4 rounds: 4 fast, 2 medium, 2 exhaustive):
 3 deleted vars, 3 deleted constraints, 0 added constraints, 3 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 12 implications, 0 cliques
presolved problem has 7 variables (3 bin, 0 int, 0 impl, 4 cont) and 9 constraints
      9 constraints of type <linear>
Presolving Time: 0.02

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
p 0.0s|     1 |     0 |     0 |     - |   locks|   0 |   7 |   9 |   9 |   0 |  0 |   0 |   0 | 1.000000e+01 | 1.200000e+01 |  20.00%| unknown
p 0.0s|     1 |     0 |     0 |     - | vbounds|   0 |   7 |   9 |   9 |   0 |  0 |   1 |   0 | 1.000000e+01 | 1.100000e+01 |  10.00%| unknown
  0.0s|     1 |     0 |     3 |     - |   646k |   0 |   7 |   9 |   9 |   0 |  0 |   2 |   0 | 1.000000e+01 | 1.100000e+01 |  10.00%| unknown
  0.0s|     1 |     0 |     7 |     - |   651k |   0 |   7 |   9 |  10 |   1 |  1 |   2 |   0 | 1.000000e+01 | 1.100000e+01 |  10.00%| unknown
  0.0s|     1 |     0 |    11 |     - |   666k |   0 |   7 |   9 |  11 |   2 |  2 |   2 |   0 | 1.000000e+01 | 1.100000e+01 |  10.00%| unknown
  0.0s|     1 |     0 |    18 |     - |   679k |   0 |   7 |   9 |  12 |   3 |  3 |   2 |   0 | 1.010040e+01 | 1.100000e+01 |   8.91%| unknown
  0.0s|     1 |     0 |    18 |     - |   679k |   0 |   7 |   9 |  12 |   3 |  3 |   2 |   0 | 1.010040e+01 | 1.100000e+01 |   8.91%| unknown
  0.0s|     1 |     0 |    23 |     - |   686k |   0 |   7 |   9 |  14 |   5 |  4 |   2 |   0 | 1.045190e+01 | 1.100000e+01 |   5.24%| unknown
r 0.0s|     1 |     0 |    23 |     - |shifting|   0 |   7 |   9 |  14 |   5 |  4 |   2 |   0 | 1.045190e+01 | 1.100000e+01 |   5.24%| unknown
  0.0s|     1 |     0 |    23 |     - |   686k |   0 |   7 |   9 |  14 |   5 |  4 |   2 |   0 | 1.045190e+01 | 1.100000e+01 |   5.24%| unknown
  0.0s|     1 |     0 |    29 |     - |   686k |   0 |   7 |   9 |  13 |   5 |  4 |   2 |   0 | 1.064562e+01 | 1.100000e+01 |   3.33%| unknown
  0.0s|     1 |     0 |    29 |     - |   686k |   0 |   7 |   9 |  12 |   5 |  4 |   2 |   0 | 1.064562e+01 | 1.100000e+01 |   3.33%| unknown
  0.0s|     1 |     0 |    35 |     - |   701k |   0 |   7 |   9 |  14 |   7 |  5 |   2 |   0 | 1.076196e+01 | 1.100000e+01 |   2.21%| unknown
  0.0s|     1 |     0 |    35 |     - |   701k |   0 |   7 |   9 |  14 |   7 |  5 |   2 |   0 | 1.076196e+01 | 1.100000e+01 |   2.21%| unknown
  0.0s|     1 |     0 |    37 |     - |   705k |   0 |   7 |   9 |  14 |   9 |  6 |   2 |   0 | 1.100000e+01 | 1.100000e+01 |   0.00%| unknown
 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
  0.0s|     1 |     0 |    37 |     - |   705k |   0 |   7 |   9 |  14 |   9 |  6 |   2 |   0 | 1.100000e+01 | 1.100000e+01 |   0.00%| unknown

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 0.04
Solving Nodes      : 1
Primal Bound       : +1.10000000000000e+01 (3 solutions)
Dual Bound         : +1.10000000000000e+01
Gap                : 0.00 %

Problem: 
- Lower bound: -inf
  Upper bound: 11.0
  Number of objectives: 1
  Number of constraints: 0
  Number of variables: 10
  Sense: unknown
Solver: 
- Status: ok
  Message: optimal solution found
  Termination condition: optimal
  Id: 0
  Error rc: 0
  Time: 0.04
  Gap: 0.0
  Primal bound: 11.0
  Dual bound: 11.0
  Transformation time: 0.003754854202270508
Solution: 
- number of solutions: 0
  number of solutions displayed: 0
```

2024-05-07 15:27 UTC, ZedongPeng commented on gdplib/jobshop/benchmark_result/2024-05-06_21-01-21/gdpopt.gloa_scip.json
> +{"Problem": [{"Name": "unknown", "Lower bound": 11.0, "Upper bound": 11.0, "Number of objectives": 1, "Number of constraints": 9, "Number of variables": 10, "Number of binary variables": 6, "Number o
No problem. I will add the name of the GDP problems in `pymo_examples`.
Hi @AlbertLee125 . Could you add the name of the rest of the models? Since there are many PRs open, I don't create conflicts.

2024-05-07 15:30 UTC, ZedongPeng commented on gdplib/jobshop/model_size_report.md
Sure. No problem. As long as we have the `JSON` file, we can do whatever we want.

2024-05-08 13:25 UTC, ZedongPeng commented on gdplib/jobshop/model_size_report.md
I will upload the Python script for the benchmarking summary after we get all the benchmark results.

2024-05-08 16:20 UTC, ZedongPeng commented
I think this PR is ready to be merged.

2024-05-16 19:46 UTC, bernalde approved these changes

2024-05-16 19:46 UTC, bernalde commented on gdplib/disease_model/disease_model.py
Is there any way that the black format leaves this parameter as they are? It looks way better this way.

2024-05-16 19:46 UTC, merged