pushing to upstream on new branch Methanol
SECQUOIA/gdplib pull request #23
Opened 2024-05-08 14:11 UTC by parkyr

Adding documentation try 1

2024-05-08 14:12 UTC, parkyr commented on gdplib/methanol/methanol.py
> +        ----------
is it better to keep these in-line instead of keeping a long list like this? For now, kept in-line original comments and added this list.

2024-05-08 14:13 UTC, parkyr commented on gdplib/methanol/methanol.py
> +        K : float
clarifications on units and constant values are needed. To be added later

2024-05-08 16:30 UTC, ZedongPeng requested changes

2024-05-08 16:30 UTC, ZedongPeng commented on gdplib/methanol/methanol.py
> +    """
This docstring is not in the numpy doc style.
https://numpydoc.readthedocs.io/en/latest/format.html

2024-05-08 22:27 UTC, parkyr commented on gdplib/methanol/methanol.py
> +            Capacity redundancy.
This attribute is not used in the model

2024-05-09 15:08 UTC, bernalde requested changes
Good first series of commits. Please address the comments I made and I will respond yours separately.

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +# Methanol production example from https://doi.org/10.1016/0098-1354(95)00219-7
I would move this to the file header instead in """ """ commenting blocks intead

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +# This model solves a methanol production process with minimum purity of 90% and amount of 1000 tons/day requirements. The structure contains 19 units; two feedstocks, two compressor types (single st
units inside square brackets

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +# Example 3 from source paper: Turkay, M., Grossmann, I. E. (1996). Logic-based MINLP algorithms for the optimal synthesis of process networks. Computers and Chemical Engineering, 125, 959-978. https
Check how we are adding references from other PRs

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +            Capacity redundancy.
Let's add a comment in the file for that, but leave the attribute as it is. This PR is not to modify the code itself, just documentation

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        cp : float
Missing units

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +            Cost of water for cooling. ($ / 10^9 kJ)
Square brackets

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        m.flows = pe.Var(m.streams, bounds=(0, 20), doc='Flowrates (kg-mol/hr)')
square brackets

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        m.temps = pe.Var(m.streams, bounds=(3, 9), doc='Temperature')
Missing units

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        flow_1['H2'] = 0.6
Extra space should we sorted out by black

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        flow_2 = dict() # Feed 2 (expensive feedstock; component percentages)
Molar? Volume? Mass?

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        b.heat_duty = pe.Var(bounds=(0, 50), doc='Heat duty')
Units?

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        The Pyomo model with the solutions enumerated.
Enumerated?

2024-05-09 15:08 UTC, bernalde commented on gdplib/methanol/methanol.py
> +    Solve the methanol production model using GDPopt.
It uses LOA, so please specify here

2024-05-09 15:09 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        ----------
It is better to have them listed here, such that we can easily know what they are when seeing the function documentation

2024-05-09 16:03 UTC, parkyr commented on gdplib/methanol/methanol.py
> +        flow_1['H2'] = 0.6
Could you clarify? Not sure what this means

2024-05-09 16:04 UTC, parkyr commented on gdplib/methanol/methanol.py
> +        flow_2 = dict() # Feed 2 (expensive feedstock; component percentages)
these are unitless / composition fractions. Leaving an in-line comment to clarify

2024-05-09 16:06 UTC, parkyr commented on gdplib/methanol/methanol.py
> +        flow_2 = dict() # Feed 2 (expensive feedstock; component percentages)
Oh you meant which fraction. Will add clarifications

2024-05-30 19:33 UTC, parkyr commented on gdplib/methanol/methanol.py
> +        flow_1['H2'] = 0.6
NVM I understand what this means now!

2024-05-30 19:34 UTC, parkyr commented on gdplib/methanol/methanol.py
> +        cp : float
gamma is a unitless ratio

2024-05-30 20:02 UTC, parkyr commented on gdplib/methanol/methanol.py
> +        The Pyomo model with the solutions enumerated.
Removed.

2024-05-31 12:34 UTC, bernalde requested changes
Good work, there are a few changed to be made and some duplicated constraints here and there

2024-05-31 12:34 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        c.add(m.component_flows[1, 'CO'] == m.flow_1_composition['CO'] * m.flows[1])
Why is this constraint duplicated?

2024-05-31 12:34 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        Objective function to maximize profit by minimizing costs and maximizing revenue ($1000 unit per year).
Units in []

2024-05-31 12:34 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        setattr(block, 'expansion_valve_' + str(u), b)
Why is this duplicated?

2024-05-31 12:34 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        b.vapor_pressure = pe.Var(
Units missing here and below

2024-05-31 15:08 UTC, parkyr commented on gdplib/methanol/methanol.py
> +        c.add(m.component_flows[1, 'CO'] == m.flow_1_composition['CO'] * m.flows[1])
removed

2024-05-31 15:08 UTC, parkyr commented on gdplib/methanol/methanol.py
> +        setattr(block, 'expansion_valve_' + str(u), b)
removed

2024-05-31 15:29 UTC, parkyr commented
Thanks for the quick review. Looks like some duplicates were created when I tried to resolve conflicts with the master branch; merging resulted in duplicates of some lines that I missed. Please review with this in mind. Thank you!

2024-06-24 16:54 UTC, parkyr commented
Issue #42 created: 

the methanol results are infeasible in both master and methanol branch.

2024-06-24 18:38 UTC, bernalde requested changes
There are a number of removed lines of code, besides the problem being now infeasible. Let's add the lines that were removed, and we can figure out the infeasibility later. I would suggest for the second one trying global LOA instead (it is very non-convex, so this might be the reason why the problem is infeasible). Another choice could be enumeration.

2024-06-24 18:38 UTC, bernalde commented on gdplib/methanol/methanol.py
> -            raise InfeasibleError(
Why did we remove this check?

2024-06-24 18:38 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        self.build_stream_doesnt_exist_con(
Why are these constraints removed?

2024-06-24 18:38 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Why is this term removed?

2024-06-24 18:38 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Why is this term removed?

2024-06-24 18:38 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Why is this term removed?

2024-06-24 18:38 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Why is this term removed?

2024-06-24 18:38 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Why is this term removed?

2024-06-24 19:35 UTC, parkyr commented on gdplib/methanol/methanol.py
> -        c.add(m.component_flows[1, 'CO'] == m.flow_1_composition['CO'] * m.flows[1])
this is the same line of code as above.
> c.add(m.component_flows[1, 'CO'] == m.flow_1_composition['CO'] * m.flows[1])

2024-06-24 19:36 UTC, parkyr commented on gdplib/methanol/methanol.py
> -        e -= (
this is repeat from code below

2024-06-25 14:03 UTC, parkyr commented on gdplib/methanol/methanol.py
> -            raise InfeasibleError(
It is a duplicate of above

2024-06-25 14:03 UTC, parkyr commented on gdplib/methanol/methanol.py
> -        self.build_stream_doesnt_exist_con(
duplicate of above

2024-06-25 14:04 UTC, parkyr commented on gdplib/methanol/methanol.py
> -        e -= (
duplicate of above

2024-06-25 14:04 UTC, parkyr commented on gdplib/methanol/methanol.py
> -        e -= (
duplicate of above

2024-06-25 14:04 UTC, parkyr commented on gdplib/methanol/methanol.py
> -        e -= (
duplicate lines of above

2024-06-25 14:05 UTC, parkyr commented on gdplib/methanol/methanol.py
> -        e -= (
duplicate lines of above

2024-06-25 14:10 UTC, parkyr commented
> There are a number of removed lines of code, besides the problem being now infeasible. Let's add the lines that were removed, and we can figure out the infeasibility later. I would suggest for the second one trying global LOA instead (it is very non-convex, so this might be the reason why the problem is infeasible). Another choice could be enumeration.

The lines removed were duplicate lines. I tried enumerate_solutions(), that also gave us infeasible soln.

2026-05-08 03:21 UTC, bernalde requested changes
Blocking issues:
- The PR currently does not merge into `main`; `git merge-tree origin/main HEAD` reports a content conflict in `gdplib/methanol/methanol.py`.
- The methanol package public API is broken because `build_model()` was removed while `gdplib/methanol/__init__.py` still imports it. This makes `import gdplib` and `from gdplib.methanol import build_model` fail.

Nonblocking issues:
- `python -m black -S -C --check --diff gdplib/methanol/methanol.py` would reformat the changed file, starting with trailing whitespace in the new module docstring.

Questions:
- None.

Tests run:
- `python -c "from gdplib.methanol import build_model"` on the fetched PR head: failed with `ImportError: cannot import name 'build_model'`.
- `python -c "import gdplib"` on the fetched PR head: failed with the same `ImportError` through `gdplib/methanol/__init__.py`.
- `git merge-tree origin/main HEAD`: failed with a content conflict in `gdplib/methanol/methanol.py`.
- `pytest tests/ -v --tb=short` on the fetched PR head: could not run meaningful tests because this stale PR head has no `tests/` directory; current `main` documents `pytest tests/`, but the PR cannot be merged to run the suite on the merge result.
- `python3.12 -m pytest tests/ -v --tb=short`: could not run because the local Python 3.12 environment has no `pytest`; `python3.12 -c "from gdplib.methanol import build_model"` also could not get past missing `pyomo` in that interpreter. The Python environment with dependencies installed is Python 3.13.5, outside the project’s supported `<3.13` range, but the `build_model` import failure above is independent of Python-version support.

This PR should not be merged as-is. I would not merge this until the blocking issues above are addressed.

2026-05-08 03:21 UTC, bernalde commented on gdplib/methanol/methanol.py
> -def build_model():
Blocking: This removes the `build_model()` public entry point while `gdplib/methanol/__init__.py` still imports and exports it. As a result, both `from gdplib.methanol import build_model` and the CI smoke test `import gdplib` fail with `ImportError`, and it breaks the repository convention documented in `README.md` that model packages expose `build_model`. Please restore this function, including the Big-M suffix setup from current `main`, or update the package exports, tests, and documentation if the public API is intentionally changing.

2026-05-08 03:29 UTC, bernalde commented on gdplib/methanol/methanol.py
> -def build_model():
Addressed in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045. I merged current main into the PR, restored `build_model()` in `gdplib/methanol/methanol.py` with the Big-M suffix setup, and added a direct regression test in `tests/test_module_imports.py::TestModelConstruction::test_methanol_model_construction`. Verified with `python -c "from gdplib.methanol import build_model; m = build_model(); print(type(m).__name__)"`, `python -c "import gdplib; print("'import ok"')"`, targeted pytest, and `python -m pytest tests/ -v --tb=short`.

2026-05-08 03:29 UTC, bernalde commented on gdplib/methanol/methanol.py
> +            Cost of water for cooling. ($ / 10^9 kJ)
Addressed in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045. The methanol documentation now uses bracketed unit notation where units are documented, and the changed methanol file was formatted with Black. No model behavior was changed for this item.

2026-05-08 03:29 UTC, bernalde commented on gdplib/methanol/methanol.py
> -            raise InfeasibleError(
Not re-added. The removed check is a duplicate `raise InfeasibleError` immediately after the same error is raised, so restoring it would leave unreachable duplicate code. I kept the duplicate removal in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045 and verified the branch with `python -m pytest tests/ -v --tb=short`.

2026-05-08 03:29 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        m.flows = pe.Var(m.streams, bounds=(0, 20), doc='Flowrates (kg-mol/hr)')
Addressed in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045. The documented units in the methanol class and component docs use square brackets where units apply, and Black was run on `gdplib/methanol/methanol.py`.

2026-05-08 03:30 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Not re-added. This removed objective term duplicates the expensive-reactor variable-cost term already present nearby, so restoring it would double-count the cost. Kept the duplicate removal in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045; `python -m pytest tests/ -v --tb=short` passes.

2026-05-08 03:30 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Not re-added. This removed objective term duplicates the same cheap-reactor variable cost already present immediately above, so restoring it would double-count the cost. Kept the duplicate removal in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045; `python -m pytest tests/ -v --tb=short` passes.

2026-05-08 03:30 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Not re-added. This removed objective term repeats an existing feed-compressor electricity-cost term, so restoring it would double-count that cost. Kept the duplicate removal in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045; `python -m pytest tests/ -v --tb=short` passes.

2026-05-08 03:30 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        self.build_stream_doesnt_exist_con(
Not re-added. These `build_stream_doesnt_exist_con` calls were duplicate constraints for streams that are already zeroed in the same disjunct. Reintroducing them would add redundant constraints without changing the model. Kept the duplicate removal in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045; `python -m pytest tests/ -v --tb=short` passes.

2026-05-08 03:30 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Not re-added. This removed objective term repeats an existing recycle-compressor or heat-duty cost term in the objective, so restoring it would double-count that cost. Kept the duplicate removal in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045; `python -m pytest tests/ -v --tb=short` passes.

2026-05-08 03:30 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Not re-added. This removed objective term repeats an existing two-stage feed-compressor cooling-cost term, so restoring it would double-count that cost. Kept the duplicate removal in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045; `python -m pytest tests/ -v --tb=short` passes.

2026-05-08 03:30 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        c.add(m.component_flows[1, 'CO'] == m.flow_1_composition['CO'] * m.flows[1])
Addressed by keeping the duplicate line removed in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045. The CO composition constraint already appears once in `gdplib/methanol/methanol.py`, and the branch now passes `python -m pytest tests/ -v --tb=short`.

2026-05-08 03:31 UTC, bernalde commented
Discussion comment replies:

- https://github.com/SECQUOIA/gdplib/pull/23#issuecomment-2142505733: Addressed in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045. I merged current `main` into the PR branch and resolved the methanol conflict, keeping the legitimate duplicate removals while restoring the missing public API.
- https://github.com/SECQUOIA/gdplib/pull/23#issuecomment-2187010293: Not addressed in code here. Methanol solve infeasibility is already tracked in #42 and is outside this documentation/API cleanup; this PR now preserves model construction and import behavior without changing the solve path.
- https://github.com/SECQUOIA/gdplib/pull/23#issuecomment-2189071998: Addressed where in scope in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045. I kept the duplicate code and duplicate objective terms removed, restored only the non-duplicate `build_model()` entry point, and added `tests/test_module_imports.py::TestModelConstruction::test_methanol_model_construction`.

Verification:
- `python -c "from gdplib.methanol import build_model; m = build_model(); print(type(m).__name__)"`
- `python -c "import gdplib; print('import ok')"`
- `python -m pytest tests/test_basic.py::TestGDPlibImports::test_main_import tests/test_module_imports.py::TestModelConstruction::test_methanol_model_construction -v --tb=short`
- `python -m pytest tests/ -v --tb=short`

2026-05-08 04:39 UTC, bernalde approved these changes
Re-review summary:
1. blocking issues: none.
2. nonblocking issues: noted inline for Pixi platform coverage and the constructor docstring shape. Also worth cleaning up later: `gdplib/methanol/methanol.py` still has a stale `sys.version_info.minor >= 6` assertion even though this PR drops support to Python 3.10+.
3. questions: none.
4. tests run and outcomes: `pixi run test-methanol` passed, 1 passed; `pixi run test-imports` passed, 67 passed; `pixi run lint` passed, with the existing nonfatal flake8 report emitted under `--exit-zero`; `pixi run test` passed, 214 passed with 4 existing README warnings. GitHub checks are also green for lint, Python 3.10, 3.11, 3.12, coverage, and pip installation.
5. merge: no blocking issues; this PR is merge-ready as-is.

2026-05-08 04:39 UTC, bernalde commented on pixi.toml
> +platforms = ["linux-64"]
Nonblocking: The README now recommends Pixi as the development environment, but this workspace is limited to `linux-64`. That will make `pixi install` fail for macOS and Windows contributors even though the package metadata remains OS independent. Consider adding the common platforms (`osx-64`, `osx-arm64`, `win-64`) and regenerating `pixi.lock`, or document this as a Linux-only development environment.

2026-05-08 04:39 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        Parameters
Nonblocking: `MethanolModel.__init__` takes no parameters, but the docstring has a `Parameters` section listing attributes initialized inside the method. That can mislead generated docs and future maintainers about the API. Consider changing this to an attributes/implementation-notes section, or keep only a short constructor docstring and move the model description to the module docstring or README.

2026-05-08 04:47 UTC, bernalde commented on gdplib/methanol/methanol.py
> +            Cost of water for cooling. ($ / 10^9 kJ)
Addressed previously in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045. The methanol documentation now uses bracketed unit notation where units are documented. No additional code change was needed in https://github.com/SECQUOIA/gdplib/commit/dd8f4ecc94d120e5921a9a20f1f1c8ede88b7796. Verification rerun: `pixi run test-methanol`, `pixi run test`, and `pixi run lint` all passed.

2026-05-08 04:47 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        m.flows = pe.Var(m.streams, bounds=(0, 20), doc='Flowrates (kg-mol/hr)')
Addressed previously in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045. The affected methanol documentation now uses square-bracket unit notation, and this follow-up did not need another unit-doc change. Verification rerun: `pixi run test-methanol`, `pixi run test`, and `pixi run lint` all passed.

2026-05-08 04:47 UTC, bernalde commented on gdplib/methanol/methanol.py
> -        e -= (
Not addressed with a code change. The removed objective term duplicates an existing feed-compressor electricity-cost term, so restoring it would double-count that cost. The latest follow-up commit https://github.com/SECQUOIA/gdplib/commit/dd8f4ecc94d120e5921a9a20f1f1c8ede88b7796 leaves the objective math unchanged. Verification rerun: `pixi run test-methanol`, `pixi run test`, and `pixi run lint` all passed.

2026-05-08 04:47 UTC, bernalde commented on pixi.toml
> +platforms = ["linux-64"]
Addressed in https://github.com/SECQUOIA/gdplib/commit/dd8f4ecc94d120e5921a9a20f1f1c8ede88b7796. I documented that the committed Pixi environment currently targets `linux-64` in https://github.com/SECQUOIA/gdplib/blob/dd8f4ecc94d120e5921a9a20f1f1c8ede88b7796/README.md#development-setup and https://github.com/SECQUOIA/gdplib/blob/dd8f4ecc94d120e5921a9a20f1f1c8ede88b7796/AGENTS.md#environment. I did not expand Pixi platforms or regenerate the lock in this PR because documenting the Linux-only lock scope is the smallest change and avoids platform-lock churn. Verification: `pixi run test-methanol`, `pixi run test`, and `pixi run lint` all passed.

2026-05-08 04:47 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        Parameters
Addressed in https://github.com/SECQUOIA/gdplib/commit/dd8f4ecc94d120e5921a9a20f1f1c8ede88b7796. I replaced the misleading `MethanolModel.__init__` parameter-style docstring with a short constructor docstring in https://github.com/SECQUOIA/gdplib/blob/dd8f4ecc94d120e5921a9a20f1f1c8ede88b7796/gdplib/methanol/methanol.py#L60-L66. The stale `sys.version_info` guard was removed from the same module in this commit. Verification: `pixi run test-methanol`, `pixi run test`, and `pixi run lint` all passed.

2026-05-08 04:47 UTC, bernalde commented
Discussion comment follow-up after https://github.com/SECQUOIA/gdplib/commit/dd8f4ecc94d120e5921a9a20f1f1c8ede88b7796:

- https://github.com/SECQUOIA/gdplib/pull/23#issuecomment-2142505733: Addressed previously in https://github.com/SECQUOIA/gdplib/commit/41881ef7acf9482084bccff30de2760287848045; duplicate conflict artifacts were reviewed and the branch keeps the non-duplicate fixes. No additional duplicate-restoration change was needed in this follow-up.
- https://github.com/SECQUOIA/gdplib/pull/23#issuecomment-2187010293: Not addressed in this commit. The methanol infeasibility is tracked separately in https://github.com/SECQUOIA/gdplib/issues/42 and remains out of scope for this review-response cleanup.
- https://github.com/SECQUOIA/gdplib/pull/23#issuecomment-2189071998: Partially addressed previously by restoring the needed removed code while leaving the duplicate objective-cost term out to avoid double counting. This follow-up commit only documents the Pixi platform scope and cleans up stale methanol API/runtime documentation.
- https://github.com/SECQUOIA/gdplib/pull/23#issuecomment-4403073856: Superseded by this follow-up reply set. Current verification: `pixi run test-methanol`, `pixi run test`, and `pixi run lint` all passed.
- https://github.com/SECQUOIA/gdplib/pull/23#pullrequestreview-4249531712: Addressed in https://github.com/SECQUOIA/gdplib/commit/dd8f4ecc94d120e5921a9a20f1f1c8ede88b7796 by removing the stale `sys.version_info` assertions and unused `sys` import from `gdplib/methanol/methanol.py`.

2026-05-08 04:54 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        Parameters
Addressed. The constructor docstring was changed in https://github.com/SECQUOIA/gdplib/commit/dd8f4ecc94d120e5921a9a20f1f1c8ede88b7796 to remove the misleading `Parameters` section and keep only a short constructor docstring. I also added a repository-level rule in https://github.com/SECQUOIA/gdplib/commit/b82ff4b5f3c8f0f30a6ce77a7dc4b393fc263bc4 so future agent edits document constructor-created attributes as implementation notes, module docs, or README content instead of callable parameters. Verification: `pixi run test-methanol`, `pixi run lint-black`, and `pixi run lint-typos` passed.

2026-05-08 04:59 UTC, bernalde commented on gdplib/methanol/methanol.py
> +        K : float
Addressed in https://github.com/SECQUOIA/gdplib/commit/7faf74c268262d9ed506ff81d8e43a604393fc43. I added a `Units and Constants` section to https://github.com/SECQUOIA/gdplib/blob/7faf74c268262d9ed506ff81d8e43a604393fc43/gdplib/methanol/README.md#units-and-constants documenting the model scaling, constructor constant values, units or equation roles, and feed molar fractions. This keeps the clarification out of `MethanolModel.__init__`, so generated docs do not treat these values as constructor parameters. Verification: `pixi run lint-typos` and `pixi run test-methanol` passed.

2026-05-08 04:59 UTC, bernalde commented on pixi.toml
> +platforms = ["linux-64"]
Addressed further in https://github.com/SECQUOIA/gdplib/commit/7faf74c268262d9ed506ff81d8e43a604393fc43. The README and `AGENTS.md` already document the Pixi environment as Linux-only; I also added a comment directly above `platforms = ["linux-64"]` in https://github.com/SECQUOIA/gdplib/blob/7faf74c268262d9ed506ff81d8e43a604393fc43/pixi.toml#L6-L8 so contributors see the platform scope at the manifest line. I did not add macOS or Windows platforms in this PR because that would require lock regeneration and broader platform validation. Verification: `pixi run lint-typos` and `pixi run test-methanol` passed.

2026-05-08 05:12 UTC, bernalde approved these changes

2026-05-08 05:17 UTC, merged