Fixing typos and adding documentation to hda file
SECQUOIA/gdplib pull request #26
Opened 2024-05-16 22:41 UTC by parkyr

first round of documentation to hda file, including header and function documentation.
some typos were fixed as well in this pull request.

2024-05-16 23:15 UTC, bernalde commented
Because of the recent PR merged by @ZedongPeng there are conflicts in this branch now. I would suggest you to figure it out with @parkyr before getting this through review

2024-05-16 23:16 UTC, ZedongPeng commented
No problem. I will help Yirang resolve the conflicts.

2024-05-17 15:40 UTC, ZedongPeng commented
Great. You made it. @parkyr

2024-05-18 20:14 UTC, bernalde requested changes
Some small changes are suggested but more importantly, since so many changes are made I want you to verify that the coeds still run. You have the original slide deck to compare.

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        permeability [kg-mole/m**2-min-mpa]
mpa as mi milli Pascalas or mega pascast, it should be mPa otherwise MPa

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        doc="heat of vaporization [kj per kg-mol]",
Let's be consistent with units. Instead of per then put all the denominator in parenthesis.

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        heat of reaction [kj per kg-mol]
Joule is uppercased (J) in SI

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        small number to avoid div. by zero
divison

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        heat capacities [kj per kg-mol-k]
Kelvin is uppercased (K) in SI

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        doc="electricity requirement [kw]",
Watts is uppercased (W) in SI

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        doc="reactor volume [cubic meter]",
m**3

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        doc="reactor pressure [mega-pascal]",
MPa

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +            # actual number of trays (gillilands approximation)
Gilliland

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        initialize=3600.0 * 8500.0 * 1.0e-12 / 60.0, doc="unit change on temp"
We have in some places temp, other places temp., other temperature. Let's standardize it. Moreover, which units are boing converted here?

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +            [rct], m.str, m.compon, rule=rctcns, doc="consumption rate of key comp."
In some places we have comp., others components.

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +    m.meathane_purge_value = Param(
methane*

2024-05-18 20:14 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +    m.meathane_purge_value = Param(
Make sure that mistake is corrected everywhere the function is called

2024-05-28 14:35 UTC, parkyr commented on gdplib/hda/HDA_GDP_gdpopt.py
> +    m.meathane_purge_value = Param(
Thank you for catching this. Corrected (3 instances in the code).

2024-05-30 17:26 UTC, parkyr commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        doc="heat of vaporization [kj per kg-mol]",
revised all units to numerator/denominator, and for any product of units kept them connected with -. (ex. kJ/kg-mol-K)

2024-05-30 17:31 UTC, parkyr commented on gdplib/hda/HDA_GDP_gdpopt.py
> +            [rct], m.str, m.compon, rule=rctcns, doc="consumption rate of key comp."
changed to components

2024-05-30 18:14 UTC, parkyr commented
I ran the code after the changes. The code runs, but it's giving me a slightly different obj value from the slidedeck; objective value for slidedeck: 5966.51; the objective value result: 5801.27. 

I compared it with the the original (unmodified) file from master branch, and the values match. The code was not affected from the documentation modifications.

2024-05-31 12:36 UTC, bernalde commented
This might arise from the subsolver that you are using, and whether it has improved since the time that previous table was made. Together with @ZedongPeng try to run all the different solvers to replicate the same results as in the table

2024-05-31 12:41 UTC, bernalde requested changes

2024-05-31 12:41 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
>          guess composition values
I suppose there are molar compositions? If so [mol/mol]

2024-05-31 12:41 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        doc="flash-Key component matches",
Why uppercasing this?

2024-05-31 19:31 UTC, ZedongPeng commented
Hi @parkyr . Have you run the code before the changes? Does the optimal solution (before changes) equal `5966.51` or `5801.27`?
You can go back to the old code with `git checkout master`.

2024-05-31 20:49 UTC, parkyr commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        doc="flash-Key component matches",
when made changes for unit -K, it got replaced as well. Went through document to fix those cases.

2024-05-31 20:50 UTC, bernalde commented on gdplib/hda/HDA_GDP_gdpopt.py
> +        doc="flash-Key component matches",
No problem, it is usually good to check what changes are committed into the repo before staging them

2024-05-31 21:03 UTC, parkyr commented
Hi @ZedongPeng, yes I did run the code from the master branch and it gives me 5801.27. I'll do some digging and see if I can recreate while you are away.

2024-06-08 21:18 UTC, ZedongPeng commented
Hi @parkyr . Have you resolved this problem? I diff-checked the code line by line and didn't find any change that would result in a different result. Have you compared the log of GDPOpt before and after the changes? If you upload the logs in this PR, I can help you check them.

Btw, if you are using two different Python virtual environments in `Anaconda` (one for the `hda` branch and the other for the `master` branch), it might be worth checking if you are using the same version of `Pyomo`.

2024-06-24 14:30 UTC, parkyr commented
Seems like the metrics of the problem are different in README.md and the results. 

README: 
| Problem   | vars | Bool | bin | int | cont | cons | nl | disj | disjtn |
|-----------|------|------|-----|-----|------|------|----|------|--------|
| HDA Model | 733 | 12 | 0 | 0 | 721 | 728 | 151 | 12 | 6 |
Obj: 5966.51

Results (master and hda branches): 
| Problem   | vars | Bool | bin | int | cont | cons | nl | disj | disjtn |
|-----------|------|------|-----|-----|------|------|----|------|--------|
| HDA Model | **721** | 12 | 0 | 0 | **709** | 728 | 151 | 12 | 6 |
Obj: 5801.27

2024-06-24 17:04 UTC, parkyr commented
> Seems like the metrics of the problem are different in README.md and the results.
> 
> README:
> Problem 	vars 	Bool 	bin 	int 	cont 	cons 	nl 	disj 	disjtn
> HDA Model 	733 	12 	0 	0 	721 	728 	151 	12 	6
> Obj: 5966.51 									
> 
> Results (master and hda branches):
> Problem 	vars 	Bool 	bin 	int 	cont 	cons 	nl 	disj 	disjtn
> HDA Model 	_**721**_ 	12 	0 	0 	_**709**_ 	728 	151 	12 	6
> Obj: 5801.27

Cross-checked with the presentation and confirmed the results table values are the correct ones. 
Changes have been made in README.md to correct this.

2024-06-24 19:35 UTC, bernalde approved these changes

2024-06-24 19:35 UTC, merged