Update documentation and units
SECQUOIA/gdplib pull request #27
Opened 2024-05-17 11:21 UTC by tristantc

The pull request contains changes to the documentation of the 'kaibel_prop.py' file.

2024-05-17 15:27 UTC, bernalde commented
Please sort the conflict with the merged PRs from @ZedongPeng before we revise this

2024-05-20 14:42 UTC, bernalde requested changes
Good work. There are some lingering TODO and TOCHECK notes that should be addressed or rewritten.
The most important one is regarding an updated logical expression system in Pyomo. If the model does not run with the current version of Pyomo, we need to update it in this PR.
Finally, put all the units between square brackets

2024-05-20 14:42 UTC, bernalde commented on gdplib/kaibel/kaibel_side_flash.py
>  """ Side feed flash """
Can you add more documentation to this and the rest of the files at the header level? Check the other models for reference

2024-05-20 14:42 UTC, bernalde commented on gdplib/kaibel/kaibel_side_flash.py
> +    # TODO: Is it computed using the Peng-Robinson equation of state?
I don't think this classifies as a TODO (as there is no action to be taken). I would add it as a Note. Moreover, I would encourage you to contact Soraya asking for these and other questions you might have

2024-05-20 14:42 UTC, bernalde commented on gdplib/kaibel/kaibel_side_flash.py
> +    # TODO: Is it computed using the Peng-Robinson equation of state?
Same comment as above

2024-05-20 14:42 UTC, bernalde commented on gdplib/kaibel/kaibel_solve_gdp.py
> +    m.Treb = m.TB0 + 5  # Reboiler temperature in K
instead of "in UNITS" let's use "[UNITS]" to standardize with other models

2024-05-20 14:42 UTC, bernalde commented on gdplib/kaibel/kaibel_solve_gdp.py
> +    m.flow_max = 1e3  # Flowrates upper bound in mol/s
See units comment above

2024-05-20 14:42 UTC, bernalde commented on gdplib/kaibel/kaibel_solve_gdp.py
> +    ## Heat capacity calculation for liquid and vapor phases using Ruczika-D method for each component in the feed, section, and tray
Can we add a link or reference to the method to the header of the file?

2024-05-20 14:42 UTC, bernalde commented on gdplib/kaibel/kaibel_solve_gdp.py
> +    # TOCHECK: pyomo.GDP Syntax
For whom is this TOCHECK note?

2024-05-20 14:42 UTC, bernalde commented on gdplib/kaibel/kaibel_solve_gdp.py
> +        # TOCHECK: Update the logic proposition constraint for the main section with the new pyomo.gdp syntax
Does the code run with the current version of Pyomo? If it doesn't then this update needs to be made in this PR

2024-05-24 22:52 UTC, bernalde requested changes
Units should be added in many missing places and between [].
The most important comment is: does this run with the last version of Pyomo without warnings from the logical expression system?

2024-05-24 22:52 UTC, bernalde commented on gdplib/kaibel/kaibel_init.py
> +from __future__ import division
We no longer neecd this as we will drop the support of Python 2

2024-05-24 22:52 UTC, bernalde commented on gdplib/kaibel/kaibel_init.py
> +# from .kaibel_prop import get_model_with_properties
This is a comment I added when debugging in your computer. Remove it please

2024-05-24 22:52 UTC, bernalde commented on gdplib/kaibel/kaibel_init.py
> +    m.Preb = 1.2  # Reboiler pressure in bar
change units to [bar], here and in the rest of the files

2024-05-24 22:52 UTC, bernalde commented on gdplib/kaibel/kaibel_init.py
> +        doc='Temperature term for vapor pressure',
Missing units here and in many other places

2024-05-24 22:52 UTC, bernalde commented on gdplib/kaibel/kaibel_solve_gdp.py
> +# from .kaibel_side_flash import calc_side_feed_flash
Remove comment

2024-05-24 22:52 UTC, bernalde commented on gdplib/kaibel/kaibel_solve_gdp.py
> +        doc="Pressure at each potential tray in bars",
Change to [units]

2024-05-24 22:52 UTC, bernalde commented on gdplib/kaibel/kaibel_solve_gdp.py
> +        doc="Liquid composition",
Missing units [mol/mol], similar below

2024-05-24 22:52 UTC, bernalde commented on gdplib/kaibel/kaibel_solve_gdp.py
> +        Vapor enthalpy for the top section in the column.
Missing units here and in many other functions

2024-05-24 22:52 UTC, bernalde commented on gdplib/kaibel/main_gdp.py
> +    m.F[1].fix(50)  # feed flowrate in mol/s
units in []

2024-08-14 01:41 UTC, bernalde commented
Does #47 supersede this? SHould we merge this beforehand?

2024-08-19 16:32 UTC, ZedongPeng approved these changes

2024-08-19 16:37 UTC, tristantc commented
> Does #47 supersede this? SHould we merge this beforehand?

Requested changes resolved in branch #47, can you merge branch #27, @bernalde?

2024-08-19 17:41 UTC, bernalde approved these changes

2024-08-19 17:41 UTC, merged