Reactor_series
SECQUOIA/gdplib pull request #28
Opened 2024-05-17 21:36 UTC by AlbertLee125

I added the reactor series with the incomplete documentation.

2024-05-17 21:38 UTC, AlbertLee125 reviewed
I ran the Python file using BARON with bigM reformulation. It gave the same results as my references in the dsda.

2024-05-19 17:48 UTC, AlbertLee125 reviewed
The documentation of the CSTR is completed. I think I need the review.

2024-05-19 21:06 UTC, bernalde requested changes
Missing file header, and several descriptions and types

2024-05-19 21:06 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
Missing file header

2024-05-19 21:06 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
>              _description_
Missing description

2024-05-19 21:06 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
>              _description_
Missing description

2024-05-19 21:06 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
>              _description_
It appears many times below

2024-05-19 21:06 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
>          disjunct : _type_
Type missing

2024-05-19 21:06 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
>              _description_
Missing description

2024-05-19 21:06 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
>  def build_cstrs(NT: int = 5) -> pyo.ConcreteModel():
This is the size parameter that would be good to vary for the benchmarking @ZedongPeng

2024-05-19 21:17 UTC, AlbertLee125 commented on gdplib/cstr/gdp_reactor.py
>              _description_
The updated version has the description.

2024-05-19 21:18 UTC, AlbertLee125 commented on gdplib/cstr/gdp_reactor.py
>              _description_
The newer version has the description.

2024-05-19 21:19 UTC, AlbertLee125 commented on gdplib/cstr/gdp_reactor.py
>          disjunct : _type_
Resolved with the newer version.

2024-05-19 21:20 UTC, AlbertLee125 commented on gdplib/cstr/gdp_reactor.py
>              _description_
The descriptions are added on the newer version.

2024-05-19 21:26 UTC, AlbertLee125 commented on gdplib/cstr/gdp_reactor.py
Header added

2024-05-20 00:09 UTC, bernalde requested changes
Move the file header to the beginning and make sure that you have added all the descriptions and types in the files, not only where I commented.

2024-05-20 00:09 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
> +"""
This should be at the very top of the file. I left the comment here because I couldn't comment elsewhere in the file

2024-05-20 00:09 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
> +                Reaction rate relation for defining pyomo model.
There were many more instances where changes needed to be made. Please review this

2024-05-20 00:13 UTC, AlbertLee125 commented on gdplib/cstr/gdp_reactor.py
> +"""
I relocated the header where it should be.

2024-05-20 00:18 UTC, AlbertLee125 commented on gdplib/cstr/gdp_reactor.py
> +                Reaction rate relation for defining pyomo model.
I am not sure what I should do. Did you mean that I have to rewrite the returns?

2024-05-20 04:36 UTC, bernalde approved these changes

2024-05-20 04:36 UTC, merged