Add toy problem README with problem details
SECQUOIA/gdplib pull request #38
Opened 2024-06-08 21:24 UTC by AlbertLee125

I added the toy problem from Linan's paper to the gdplib.

2024-06-10 22:36 UTC, ZedongPeng commented
The black format check failed. @AlbertLee125

2024-08-16 19:42 UTC, AlbertLee125 commented
The toy problem is ready to go. I changed the title to david_linan.py and changed the directory to david_linan. The spelling is failing because of the HDA_gdpopt file. Besides the hda file error, the code is ready to go.

Second thoughts: Gomez_linan is also a good name for the toy problem. They are the ones to create the given model. If you both think the title is better written as 'gomez_linan.py', please let me know.

2024-08-17 00:36 UTC, bernalde requested changes
Change all parts where it is referred to 'Toy problem'.
Does this run with the ldsda implementation?

2024-08-17 00:36 UTC, bernalde commented on gdplib/david_linan/README.md
> +## david_linan.py
Not a good name. Use ex1_linan_2023.py

2024-08-17 00:36 UTC, bernalde commented on gdplib/david_linan/README.md
> +The toy problem is a simple optimization problem that involves two Boolean variables, two continuous variables, and a non-linear objective function.
This is no longer the "toy problem"

2024-08-17 00:36 UTC, bernalde commented on gdplib/david_linan/README.md
> +The objective function of the model is originated from Problem No. 6 of Gomez's paper and Linan introduced logic proposition, logic disjunctions and the following eqautinons as the constraints.
There are typos and misspellings in this paragraph.

2024-08-17 00:36 UTC, bernalde commented on gdplib/david_linan/david_linan.py
See comments from other file

2024-08-19 17:30 UTC, AlbertLee125 commented
> Change all parts where it is referred to 'Toy problem'. Does this run with the ldsda implementation?

```
m = build_model()
    pyo.SolverFactory('gdpopt.ldsda').solve(
        m,
        minlp_solver="gams",
        minlp_solver_args=dict(solver="baron", add_options=["option optcr=0.001;"]),
        tee=True,
        starting_point=[5, 1],
        logical_constraint_list=[m.oneY1, m.oneY2],
        direction_norm='Linf',
        time_limit=900
    )
    print("Solution: alpha=", pyo.value(m.alpha), " beta=", pyo.value(m.beta))
    print("Objective function value: ", pyo.value(m.obj))
   ```
   If I set the starting point at [5,1], the code could not cross the infeasible wall of the problem. However, by setting the starting point at [1,1], the code could find the global minimum. I will mention about the infeasible wall in the documentation.

2024-08-19 17:43 UTC, bernalde requested changes

2024-08-19 17:43 UTC, bernalde commented on gdplib/ ex1_linan_2023/README.md
> +## ex1_linan.py
This is not the name of the file

2024-08-19 17:43 UTC, bernalde commented on gdplib/ ex1_linan_2023/README.md
> +The `ex1_linan.py` file is a simple optimization problem that involves two Boolean variables, two continuous variables, and a nonlinear objective function. The problem is formulated as a Generalized
This is not the name of the file

2024-08-19 17:57 UTC, AlbertLee125 commented
I changed the title and name as Example 1 Problem of Liñán (2023).

2024-08-19 20:12 UTC, bernalde approved these changes

2024-08-19 20:12 UTC, merged