Update problem size table
SECQUOIA/gdplib pull request #45
Opened 2024-08-03 21:29 UTC by ZedongPeng

This pull request updates the problem size table for each model in the README.md. 
The `kaibel` and `mod_hens` problems have multiple formulations, and assistance is needed with them.

- [ ] `kaibel` @tristantc 
- [ ] `mod_hens` @AlbertLee125

2024-08-07 20:04 UTC, ZedongPeng commented
We should also come up with a way to use the different formulations of models, like `kaibel` and `mod_hens`.

2024-08-07 20:08 UTC, AlbertLee125 commented
In this case, for the Mod HENS, it consist of the common code and there variations. I think it would be good to split the common codes into other variations and make them separately.

2024-08-14 01:39 UTC, bernalde commented
I agree with Albert, split into three models, maybe using common functions, and report them separately

2024-08-16 15:13 UTC, ZedongPeng commented
In the old readme file, there are 7 models instead of 3.
![image](https://github.com/user-attachments/assets/8fa6e24e-eed2-4a44-9697-31d21aff7fb6)

Personally, I don't suggest splitting them into different models or folders since they are different formulations of the same problem. We should do something clever, like using an `arg` to determine which formulation to use.

2024-08-18 20:31 UTC, ZedongPeng commented
This PR is ready for review, except for the `stranded_gas` problem. @bernalde 

For the `stranded_gas` problem, the setup for cases like `Gas_100`, `Gas_250`, `Gas_500`, `Gas_small`, and `Gas_large` remains unclear, even after examining the code.

Could you please update the `README.md` file with a detailed example of how to properly use these cases? @AlbertLee125

2024-09-04 17:31 UTC, AlbertLee125 commented
For the `stranded_gas` problem, the way how the problem is formulated is explained on below code.
```
if __name__ == "__main__":
    m = build_model()
    # m.module_types.pprint()
    # m.well_clusters.pprint()

    # Restrict number of module types; A, R, S, U
    # valid_modules = ['A500', 'A1000', 'A2000', 'A5000']
    # valid_modules = ['A500', 'R500', 'A5000', 'R5000']
    # valid_modules = ['U500', 'U5000']
    # valid_modules = ['U100', 'U250']
    # valid_modules = ['U1000']
    # valid_modules = ['U500']
    
    # valid_modules = ['U250']
    valid_modules = ['U100']
    for mtype in m.module_types - valid_modules:
        m.gas_consumption[:, mtype, :].fix(0)
        m.num_modules[mtype, :, :].fix(0)
        m.modules_transferred[mtype, :, :, :].fix(0)
        m.modules_purchased[mtype, :, :].fix(0)
        m.mtype_exists[mtype].deactivate()
        m.mtype_absent[mtype].binary_indicator_var.fix(1)
```

Given the code. The way that only specific units are activated is that the other units that are not valid are deactivated passing through the for loop. 

I obtained the data before running the optimization by searching `component_data_objeccts` but the numbers of variables I got seems incorrect.

```
Number of variables: 57618
Number of Boolean variables: 0
Number of binary variables: 0
Number of integer variables: 45360
Number of continuous variables: 12258
Number of constraints: 14791
Number of nonlinear constraints: 0
Number of disjuncts: 175
Number of disjunctions: 96
Number of binary variables after transformation: 175
```

| Problem   | vars | Bool | bin | int | cont | cons | nl | disj | disjtn |
|-----------|------|------|-----|-----|------|------|----|------|--------|
| Gas_100 | 8816 | 158 | 0 | 2520 | 6138 | 14925 | 1 | 158 | 96 |

I got this table from README.md

2024-09-04 23:47 UTC, ZedongPeng commented
I noticed a significant difference between your results and the ones presented in the README.md. Could you help clarify why there’s such a large discrepancy? @AlbertLee125 

Is it possible to integrate the `fix()` and `deactivate()` code in the `build_model()` function? (currently in the `main` function) Otherwise, it might be too complicated for users to create this model. Any ideas? @bernalde @AlbertLee125

2026-05-08 05:30 UTC, bernalde requested changes
Blocking issues:
- The PR is not mergeable against current main. A non-destructive merge check reports conflicts in `gdplib/cstr/README.md`, `gdplib/methanol/README.md`, and `generate_model_size_report.py`.
- `gdplib.mod_hens.build_model()` drops the previously documented case strings and now returns `None` for those inputs because unknown cases are not rejected.
- The changed Python script fails the repository Black check.

Nonblocking issues:
- A new `jobshop` README uses the wrong model title.
- A new purchasing-contract README line has a visible spelling issue.

Questions:
- None.

Tests run and outcomes:
- Discovered documented commands from `README.md` and `.github/workflows`: `pixi run test`, `pixi run lint`, `pytest tests/ -v --tb=short`, Black, flake8, and typos.
- `pixi --version`: failed, `pixi` is not installed here, so Pixi commands could not be run.
- `pytest tests/ -v --tb=short` on the PR head: failed because this stale branch has no `tests/` directory.
- `python3.12 -m pytest tests/ -v --tb=short`: failed because this Python 3.12 environment has neither `pytest` nor runtime dependencies installed.
- Targeted `mod_hens` API check with available Python 3.13 dependencies: old case strings `require_modular_integer`, `modular_option_integer`, `require_modular_discrete`, and `modular_option_discrete` all returned `None`; new case strings constructed models.
- `python generate_model_size_report.py`: passed, with existing Pyomo model-construction warnings.
- `black -S -C --target-version py310 --check --diff gdplib/mod_hens/__init__.py generate_model_size_report.py`: failed; `generate_model_size_report.py` would be reformatted.
- `flake8 gdplib/ --count --select=E9,F63,F7,F82 --show-source --statistics`: passed with 0 fatal findings.
- `flake8 gdplib/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics`: completed with existing style findings and exit-zero behavior.
- `typos --version`: failed, `typos` is not installed here.

I would not merge this until the blocking issues above are addressed.

2026-05-08 05:30 UTC, bernalde commented on gdplib/mod_hens/__init__.py
> +    elif case == "multiple_module_integer":
Blocking: This drops the previously documented `require_modular_integer` selector from the public `build_model(case=...)` API. Existing callers now get `None` instead of a model because there is no final error branch, and the same regression applies to `modular_option_integer`, `require_modular_discrete`, and `modular_option_discrete`. Keep the old names as aliases or avoid the rename, and add an `else: raise ValueError(...)` plus a focused test that every supported case returns a model.

2026-05-08 05:30 UTC, bernalde commented on generate_model_size_report.py
> +    instance_dict = {
Blocking: The repository Black command fails on this file because there are two blank lines between the imports and this block. `black -S -C --target-version py310 --check --diff gdplib/mod_hens/__init__.py generate_model_size_report.py` reports that `generate_model_size_report.py` would be reformatted. Run the configured Black command before updating the PR.

2026-05-08 05:30 UTC, bernalde commented on gdplib/jobshop/README.md
> +# GDP Distillation Column Design
Nonblocking: This title says `GDP Distillation Column Design`, but the file documents the jobshop scheduling model. Rename the heading to match the package, for example `# Jobshop Scheduling Problem`, so model-directory browsing and generated docs do not misidentify this example.

2026-05-08 05:30 UTC, bernalde commented on gdplib/med_term_purchasing/README.md
> +2. **DISCOUNT CONTRACT**: quantities below minimum amount cost RegPrice. Any additional quantity above min amount costs DiscoutPrice.
Nonblocking: `DiscoutPrice` appears to be a misspelling of `DiscountPrice`. Correcting it keeps the user-facing contract description clear and avoids a likely spell-check failure once the branch is updated against current CI.

2026-05-08 05:40 UTC, bernalde commented on gdplib/mod_hens/__init__.py
> +    elif case == "multiple_module_integer":
Addressed in https://github.com/SECQUOIA/gdplib/commit/9ada6ac0d7d4854fc1859208f7efdb9e40f5f215. `gdplib/mod_hens/__init__.py` now accepts the legacy `require_modular_*` and `modular_option_*` selectors as aliases, raises `ValueError` for unknown cases, and `tests/test_mod_hens.py` covers every supported selector plus the invalid-case path. I also documented the aliases in `gdplib/mod_hens/README.md`.

2026-05-08 05:40 UTC, bernalde commented on generate_model_size_report.py
> +    instance_dict = {
Addressed in https://github.com/SECQUOIA/gdplib/commit/9ada6ac0d7d4854fc1859208f7efdb9e40f5f215. The merge resolution removed the extra blank line in `generate_model_size_report.py`, and `black -S -C --target-version py310 --check --diff .` now passes locally.

2026-05-08 05:40 UTC, bernalde commented on gdplib/jobshop/README.md
> +# GDP Distillation Column Design
Addressed in https://github.com/SECQUOIA/gdplib/commit/9ada6ac0d7d4854fc1859208f7efdb9e40f5f215. The heading in `gdplib/jobshop/README.md` is now `# Jobshop Scheduling Problem`.

2026-05-08 05:40 UTC, bernalde commented on gdplib/med_term_purchasing/README.md
> +2. **DISCOUNT CONTRACT**: quantities below minimum amount cost RegPrice. Any additional quantity above min amount costs DiscoutPrice.
Addressed in https://github.com/SECQUOIA/gdplib/commit/9ada6ac0d7d4854fc1859208f7efdb9e40f5f215. I corrected `DiscoutPrice` to `DiscountPrice` in `gdplib/med_term_purchasing/README.md` and applied the same typo fix to the matching source comment in `gdplib/med_term_purchasing/med_term_purchasing.py`.

2026-05-08 05:41 UTC, bernalde commented
Follow-up on the existing conversation comments after https://github.com/SECQUOIA/gdplib/commit/9ada6ac0d7d4854fc1859208f7efdb9e40f5f215:

- https://github.com/SECQUOIA/gdplib/pull/45#issuecomment-2274256441: partially addressed. The PR keeps the argument-based formulation selection for `mod_hens` and `modprodnet`; `stranded_gas` remains a separate design/API documentation task.
- https://github.com/SECQUOIA/gdplib/pull/45#issuecomment-2274260928 and https://github.com/SECQUOIA/gdplib/pull/45#issuecomment-2287668306: not addressed by splitting `mod_hens` into separate packages. I kept the existing package structure because the PR documents the seven formulations through `build_model(case=...)` and now preserves the legacy aliases.
- https://github.com/SECQUOIA/gdplib/pull/45#issuecomment-2293693082: addressed. The seven `mod_hens` formulations remain in one package using the `case` argument, with compatibility aliases documented.
- https://github.com/SECQUOIA/gdplib/pull/45#issuecomment-2295381683, https://github.com/SECQUOIA/gdplib/pull/45#issuecomment-2329622676, and https://github.com/SECQUOIA/gdplib/pull/45#issuecomment-2330334886: not addressed in this commit. The `stranded_gas` case-selection behavior needs a dedicated API/documentation change so the README size counts are not based on ad hoc post-build fix/deactivate steps.
- Review summary at https://github.com/SECQUOIA/gdplib/pull/45#pullrequestreview-4249720290: addressed. The branch was merged with current `main`, conflicts were resolved, `mod_hens` compatibility and tests were added, formatting was fixed, and the README typo/title issues were corrected.

Local checks run: `pytest tests/test_mod_hens.py -v --tb=short`, `pytest tests/test_module_imports.py -v --tb=short`, `pytest tests/ -v --tb=short`, `black -S -C --target-version py310 --check --diff .`, `flake8 gdplib/ --count --select=E9,F63,F7,F82 --show-source --statistics`, and `python generate_model_size_report.py`. `typos --config ./.github/workflows/typos.toml` and Pixi commands could not be run locally because `typos` and `pixi` are not installed in this environment.

2026-05-08 05:44 UTC, bernalde commented on gdplib/mod_hens/__init__.py
> +    elif case == "multiple_module_integer":
Follow-up CI fix in https://github.com/SECQUOIA/gdplib/commit/a29faa0340a8a6c5f64302c448a4580795e255ec. The focused selector test now passes `cafaro_approx=False`, so it verifies the public case dispatch and aliases without requiring the optional IPOPT executable.

2026-05-08 05:44 UTC, bernalde commented
Follow-up after the first push: GitHub Actions failed because `tests/test_mod_hens.py` constructed the models with the default `cafaro_approx=True`, which calls IPOPT while CI intentionally does not install external solvers. I addressed that in https://github.com/SECQUOIA/gdplib/commit/a29faa0340a8a6c5f64302c448a4580795e255ec by using `cafaro_approx=False` in the focused API test.

Re-run locally after that change: `pytest tests/test_mod_hens.py -v --tb=short`, `pytest tests/ -v --tb=short`, `black -S -C --target-version py310 --check --diff tests/test_mod_hens.py gdplib/mod_hens/__init__.py generate_model_size_report.py`, and `flake8 gdplib/ --count --select=E9,F63,F7,F82 --show-source --statistics` all passed.

2026-05-08 12:04 UTC, bernalde commented
Follow-up on the size-table coverage question: addressed in https://github.com/SECQUOIA/gdplib/commit/45f4839569acc75e9a33d686c243e9e81ef205b1.

What changed:
- `stranded_gas.build_model()` now accepts the documented cases `Gas_100`, `Gas_250`, `Gas_500`, `Gas_small`, and `Gas_large`; calling `build_model()` without a case still builds the unrestricted base model.
- `generate_model_size_report.py` now uses explicit model-instance specs with args/kwargs, so models with multiple instantiations get one generated table column per documented case. `mod_hens` also uses `cafaro_approx=False` there so generating size reports does not require IPOPT.
- `gdplib/stranded_gas/README.md` now documents the public case API and has a size table regenerated from `build_model_size_report(build_model(case))` for each stranded gas case.
- Added `tests/test_stranded_gas.py` to preserve the case mapping and invalid-case behavior.

Tests run locally:
- `pytest tests/test_stranded_gas.py -v --tb=short`: 7 passed
- `pytest tests/test_mod_hens.py tests/test_stranded_gas.py -v --tb=short`: 19 passed
- `pytest tests/test_stranded_gas.py tests/test_module_imports.py -v --tb=short`: 74 passed
- `pytest tests/ -v --tb=short`: 232 passed, 1 skipped
- `black -S -C --target-version py310 --check --diff .`: passed
- `flake8 gdplib/ --count --select=E9,F63,F7,F82 --show-source --statistics`: passed
- `python generate_model_size_report.py`: passed with existing Pyomo warnings

`typos` and `pixi` are still not installed in this local environment, so I could not run those locally. I also updated the PR checklist to mark `stranded_gas` complete.

2026-05-08 12:21 UTC, bernalde requested changes
Missing optimal solution value. In general, we need to think of a way of reporting these solution systematically as a json (?) file

2026-05-08 12:21 UTC, bernalde commented on gdplib/batch_processing/README.md
> +TODO
Let's find the optimal solution and report in this PR

2026-05-08 12:21 UTC, bernalde commented on gdplib/disease_model/README.md
> +
Optimal solution missing

2026-05-08 12:21 UTC, bernalde commented on gdplib/jobshop/README.md
> +
Missing optimal solution

2026-05-08 12:21 UTC, bernalde commented on gdplib/med_term_purchasing/README.md
> +### Solution
Optimal solution, and value missing

2026-05-08 12:31 UTC, bernalde commented on gdplib/batch_processing/README.md
> +TODO
Addressed in https://github.com/SECQUOIA/gdplib/commit/85ec709991c1216d655fb29b9c85eae533ef71e0. I solved `batch_processing` through the model file’s existing `gdp.bigm` + `gams`/`baron` path in the Pixi environment. BARON reported normal completion with objective `679365.3347987866`, and the README now reports that value as the best known optimal objective.

2026-05-08 12:31 UTC, bernalde commented on gdplib/disease_model/README.md
> +
Addressed in https://github.com/SECQUOIA/gdplib/commit/85ec709991c1216d655fb29b9c85eae533ef71e0. I solved `disease_model` through the model file’s existing `gdp.bigm` + `gams`/`baron` path in the Pixi environment. BARON reported normal completion with objective `304.4162107198316`, and the README now reports that value as the best known optimal objective.

2026-05-08 12:31 UTC, bernalde commented on gdplib/jobshop/README.md
> +
Addressed in https://github.com/SECQUOIA/gdplib/commit/85ec709991c1216d655fb29b9c85eae533ef71e0. I solved `jobshop` through the model file’s existing `gdp.bigm` + `gams`/`baron` path in the Pixi environment. BARON reported normal completion with makespan objective `11.0`, and the README now reports that value as the best known optimal objective.

2026-05-08 12:31 UTC, bernalde commented on gdplib/med_term_purchasing/README.md
> +### Solution
Addressed in https://github.com/SECQUOIA/gdplib/commit/85ec709991c1216d655fb29b9c85eae533ef71e0. I solved `med_term_purchasing` through the model file’s existing `gdp.bigm` + `gams`/`baron` path in the Pixi environment. BARON reported normal completion with profit objective `6797.539701513403`, and the README now reports that value as the best known optimal objective.

2026-05-08 12:33 UTC, bernalde commented
Follow-up on the optimal-solution reporting comments: addressed in
https://github.com/SECQUOIA/gdplib/commit/85ec709991c1216d655fb29b9c85eae533ef71e0.

I solved the four models called out in the review using the Pixi environment
and each model file's existing `gdp.bigm` + `gams`/`baron` execution path:

- `batch_processing`: objective `679365.3347987866`, optimal.
- `disease_model`: objective `304.4162107198316`, optimal.
- `jobshop`: makespan objective `11.0`, optimal.
- `med_term_purchasing`: profit objective `6797.539701513403`, optimal.

The corresponding README solution sections now report these values using the
same "Best known objective value: ... (optimal)" style. I replied to each
inline review comment with the commit and solve evidence.

Pixi/local verification:
- `/home/bernalde/.pixi/bin/pixi install`: passed.
- `/home/bernalde/.pixi/bin/pixi run test-imports`: 67 passed.
- `/home/bernalde/.pixi/bin/pixi run test`: 233 passed.
- `/home/bernalde/.pixi/bin/pixi run lint-typos`: passed.
- `/home/bernalde/.pixi/bin/pixi run lint`: passed; the exit-zero flake8 style
  stage still reports existing nonfatal style findings, as expected for this
  repository task.

CI on the pushed commit is also passing for lint/style-and-typos, pip
installation, Python 3.10/3.11/3.12 tests, and coverage.

For the broader reporting-standard discussion, I created
https://github.com/SECQUOIA/gdplib/issues/105. It proposes a future structured
solution-record format, inspired by MINLPLib's solution-point metadata and Solu
files, so READMEs can eventually be generated or checked from a single source of
truth rather than hand-edited independently.

2026-05-08 12:39 UTC, bernalde approved these changes

2026-05-08 12:48 UTC, merged