Improve CSTR model
SECQUOIA/gdplib pull request #56
Opened 2024-08-21 20:46 UTC by ZedongPeng

# Changes
- Remove the redundant boolean variables in the `CSTR` model.

2024-08-21 22:27 UTC, bernalde requested changes
I would like you to review if this model can be solved by LOA as it looks similar to the changes that I made earlier with @AlbertLee125 that would fail in that.
More importantly, there are issues that are being resolved with the model right now so I would hold from merging these until we are clear in that front

2025-01-23 18:00 UTC, bernalde commented
@AlbertLee125 any news?

2025-01-24 18:29 UTC, AlbertLee125 commented
```
if __name__ == "__main__":
    m = build_model(NT=5)
    subsolver = 'scip'
    pyo.SolverFactory("gdpopt.loa").solve(
        m,
        tee=True,
        nlp_solver=subsolver,
        mip_solver=subsolver,
        minlp_solver=subsolver,
        local_minlp_solver=subsolver,
    )
```

Running the reformed code with the given script. The model can be solved by LOA and the objective found by LOA is similar to the objective solved by GDP reformulation.

2026-05-08 12:58 UTC, bernalde requested changes
1. blocking issues: Missing regression coverage for the CSTR logical rewiring.
2. nonblocking issues: Prefer using the model index set in the new recycle logic.
3. questions: None.
4. tests run and outcomes: `/home/bernalde/.pixi/bin/pixi run pytest tests/test_module_imports.py::TestModelConstruction::test_cstr_model_construction -v --tb=short` passed; `/home/bernalde/.pixi/bin/pixi run test-imports` passed; `/home/bernalde/.pixi/bin/pixi run test` passed with 233 tests; `/home/bernalde/.pixi/bin/pixi run lint-black` passed; `/home/bernalde/.pixi/bin/pixi run lint-flake8-critical` passed; `/home/bernalde/.pixi/bin/pixi run lint-typos` passed; direct CSTR `gdp.bigm` transformation passed. A `core.logical_to_linear` + `gdp.bigm` smoke test could not run in the Pixi environment because `sympy` is not installed there.
5. merge decision: I would not merge this until the blocking issues above are addressed.

2026-05-08 12:58 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
> +        return m.YR_is_recycle[n].indicator_var.implies(m.YP_is_cstr[n].indicator_var)
Blocking: This rewires the CSTR logic from the explicit `m.YP`/`m.YR` BooleanVars to the disjunct indicator variables, but the PR does not add a regression test for the changed behavior. The existing tests only verify that `build_model()` returns a Pyomo object, so a future break in logical reformulation would still pass. Please add a focused test that builds `gdplib.cstr.build_model()`, applies the supported GDP/logical reformulation path at least through `gdp.bigm`, and asserts that no active `LogicalConstraint` or `Disjunction` components remain.

2026-05-08 12:58 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
> +            1, [m.YR_is_recycle[n].indicator_var for n in range(1, NT + 1)]
Nonblocking: This duplicates the `m.N` indexing with `range(1, NT + 1)`. It is equivalent today, but it creates a second source of truth if the index set ever changes. Prefer `[m.YR_is_recycle[n].indicator_var for n in m.N]` so the logical constraint follows the model set.

2026-05-08 13:07 UTC, bernalde commented
Pushed commits:
- 7cbb788de8517082c4f445111bc95f7c0345117f - Add CSTR reformulation regression test
- 0e3a223a07d60ba971bcf7987a2e64f60c8207e3 - Merge current `main` into `improve-cstr` so the PR is tested against the current repository state

Main changes made:
- Added a CSTR regression test that builds `gdplib.cstr.build_model()`, applies `gdp.bigm`, and asserts there are no active `LogicalConstraint` or `Disjunction` components left.
- Changed the recycle logic to iterate over `m.N` instead of duplicating the index set with `range(1, NT + 1)`.
- Removed the explicit `core.logical_to_linear` call from the CSTR script path. The direct `gdp.bigm` transformation covers this model's logical/GDP reformulation without requiring `sympy`, so I did not add `sympy` as a dependency.

Tests run and results:
- `/home/bernalde/.pixi/bin/pixi run pytest tests/test_module_imports.py::TestModelConstruction::test_cstr_model_reformulates_with_bigm -v --tb=short` passed.
- `/home/bernalde/.pixi/bin/pixi run test-imports` passed: 68 tests.
- `/home/bernalde/.pixi/bin/pixi run test` passed: 234 tests.
- `/home/bernalde/.pixi/bin/pixi run lint-black` passed.
- `/home/bernalde/.pixi/bin/pixi run lint-flake8-critical` passed.
- `/home/bernalde/.pixi/bin/pixi run lint-flake8` completed with exit code 0 and reports the existing repository-wide warnings from the exit-zero lint task.
- `/home/bernalde/.pixi/bin/pixi run lint-typos` passed.

Comments intentionally not addressed:
- The earlier discussion about LOA was treated as informational because it was already answered with a successful SCIP/GDPopt LOA run. I did not add a solver-backed LOA test because SCIP/GAMS/BARON and similar solvers are optional external tools for this repository and should not become default test dependencies.
- I did not add `sympy`; the new regression covers the supported direct `gdp.bigm` path that works in the committed Pixi environment without `sympy`.

Remaining risks or follow-up items:
- GitHub Actions are still queued/running on the pushed commit.
- Solver-backed objective verification remains optional follow-up if maintainers want a separate solver-specific record.

2026-05-08 13:08 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
> +        return m.YR_is_recycle[n].indicator_var.implies(m.YP_is_cstr[n].indicator_var)
Addressed in https://github.com/SECQUOIA/gdplib/commit/7cbb788de8517082c4f445111bc95f7c0345117f. Added `test_cstr_model_reformulates_with_bigm`, which applies direct `gdp.bigm` and checks that active logical/GDP components are gone.

2026-05-08 13:08 UTC, bernalde commented on gdplib/cstr/gdp_reactor.py
> +            1, [m.YR_is_recycle[n].indicator_var for n in range(1, NT + 1)]
Addressed in https://github.com/SECQUOIA/gdplib/commit/7cbb788de8517082c4f445111bc95f7c0345117f. `one_recycle_rule` now iterates over `m.N`.

2026-05-08 13:19 UTC, bernalde commented
Follow-up verification for the original PR intent:

- The branch is pushed at `0e3a223a07d60ba971bcf7987a2e64f60c8207e3`; no additional code changes were needed after the previous push.
- All GitHub checks on this head are passing.
- The PR does address the intended cleanup if the intent is to remove redundant logical Boolean components. It does not reduce the numeric solver-facing big-M model.

Model-size impact:

| NT | BooleanVarData on `main` | BooleanVarData on this PR | Reduction | Big-M active vars / binaries / constraints |
|---:|---:|---:|---:|---:|
| 5 | 15 | 5 | 10 | unchanged: 121 / 65 / 301 |
| 10 | 30 | 10 | 20 | unchanged: 231 / 125 / 611 |
| 20 | 60 | 20 | 40 | unchanged: 451 / 245 / 1306 |
| 50 | 150 | 50 | 100 | unchanged: 1111 / 605 / 3991 |

Interpretation:

- The reduction is exactly `2 * NT` logical `BooleanVarData` objects: `YP[n]` and `YR[n]`.
- Pyomo's standard model-size report is unchanged because those removed Booleans were logical alias components, not independent numeric variables.
- On current `main`, `YP[n]` aliases `YP_is_cstr[n].indicator_var`, and `YR[n]` aliases `YR_is_recycle[n].indicator_var` for `NT=5,10,20,50`.
- After applying `gdp.bigm`, the generated `.nl` files were byte-identical between `main` and this PR for `NT=5`, `NT=10`, and `NT=20`.
- For `NT=50`, the transformed active variable, binary-variable, and constraint counts were also identical.

Conclusion:

- The default problem size (`NT=5`) is unchanged in the solver-facing algebraic model.
- Larger tested cases preserve the same reformulated model structure.
- The practical benefit is reducing redundant Pyomo logical components and avoiding the transformation deprecation warnings emitted by the old aliasing pattern.
- No `sympy` dependency is needed for this path; direct `gdp.bigm` reformulates the model in the committed Pixi environment.

Review comments:

- Blocking regression-test comment: addressed in `7cbb788de8517082c4f445111bc95f7c0345117f`.
- Nonblocking `m.N` indexing comment: addressed in `7cbb788de8517082c4f445111bc95f7c0345117f`.
- Both inline threads have replies. They are not marked resolved.

2026-05-08 13:20 UTC, bernalde approved these changes

2026-05-08 14:36 UTC, AlbertLee125 approved these changes

2026-05-08 15:44 UTC, merged