Remove associate and unused variables
SECQUOIA/gdplib pull request #57
Opened 2024-08-24 06:26 UTC by AlbertLee125

This pull request removes the `associate_binary_var` method call and the unused variables `m.Y1` and `m.Y2`. These changes simplify the code and remove unnecessary functionality.

Linan's codes involve associating the Boolean variable with Binary variable. using the indicator var would be helpful for the code to excecute logic-based Algorithms

2024-08-26 22:31 UTC, bernalde requested changes
Does this still work with the implementation of ldsda? If yes, we should merge

2024-08-27 02:21 UTC, AlbertLee125 commented
It works great for me. The output is better since this output would not be shown on the logs.
```
WARNING: implicitly casting 'Y_exists[3,centrifuge].indicator_var' value 0 to bool
```
The small batch can be improved. If it is okay, I will make another Pull Request.

2024-08-27 14:24 UTC, bernalde approved these changes

2024-08-27 14:25 UTC, bernalde commented
Yes, please create another PR for the smallbatch

2024-08-27 14:25 UTC, merged