Upload benchmark results
SECQUOIA/gdplib pull request #58
Opened 2024-08-28 21:20 UTC by ZedongPeng

# TODO
1. batch_processing
     - [ ] GLOA

2024-08-28 21:36 UTC, bernalde reviewed
Great results so far, for the solvers that involve MINLP I realized that GAMS has as default DICOPT. Let's replace it with BARON instead (at least we'll get good bounds)

2024-08-28 21:39 UTC, bernalde reviewed
For the results, if using GAMS, we should also report the subsolvers (NLP, MIP and MINLP) used

2024-08-28 21:59 UTC, ZedongPeng commented
No problem. I will also use Baron to solve the BigM and Hull reformulations. We can specify the four subsolvers (`nlp_solver`, `mip_solver`, `minlp_solver`, `local_minlp_solver`) in GDPOpt. Besides the minlp_solver, is there any other solver we should consider specifying? @bernalde

2024-08-28 22:23 UTC, bernalde commented
I think BARON is state-of-the-art in MINLP and NLP but might be too expensive, especially for local_nlp_solver.
KNITRO is the best as local goes in my opinion. And SCIP as open source.

2024-08-30 19:21 UTC, ZedongPeng commented
1. Use SCIP through GAMS for all subsolvers. 
2. Use BARON for all subsolvers.

2024-11-06 04:53 UTC, tristantc commented
Using BARON for all subsolvers.

# TODO
1. `batch_processing`
     - [ ] GLOA
2. `biofuel`
     - [ ] Not working.
3. `cstr`
     - [ ] GLOA
4. `disease_model`
     - [ ] Enumerate
5. `ex1_linan_2023`
     - [ ] Hull reformulation.
     - [ ] GLOA
     - [ ] LOA
     - [ ] LBB
     - [ ] RIC
6. `gdp_col`
     - [ ] Hull reformulation
     - [ ] GLOA
     - [ ] LBB
7. `hda`
     - [ ] Hull reformulation
     - [ ] GLOA
8. `kaibel`
     - [ ] Not working
9. `med_term_purchasing`
     - [ ] Enumerate
     - [ ] LBB
10. `methanol`
     - [ ] GLOA
11. `mod_hens`
     - [ ] Enumerate
     - [ ] GLOA
     - [ ] LBB
12. `modprodnet`
     - [ ] GLOA
13. `positioning`
     - [ ] GLOA
14. `small_batch`
     - [ ] GLOA
15. `spectralog`
     - [ ] Enumerate
     - [ ] GLOA
16. `stranded_gas`
     - [ ] Hull reformulation
     - [ ] Enumerate
     - [ ] GLOA
     - [ ] LOA
     - [ ] LBB
     - [ ] RIC
17. `syngas`
     - [ ] GLOA
     - [ ] LBB

I will open an issue for every single instance to keep progressing.

2026-05-08 16:50 UTC, bernalde commented on .gitignore
> +gdplib/*/benchmark_result/*.log
Blocking: This narrows the ignore rule from `gdplib/*/benchmark_result/` to only `*.log`, so raw benchmark JSON under package directories becomes tracked. Current packaging includes package JSON files, so these generated benchmark outputs would be shipped with GDPlib installs instead of remaining reproducible artifacts. Keep `benchmark_result/` ignored, or move a curated, documented summary into a deliberate data/docs location with package-data exclusions.

2026-05-08 16:51 UTC, bernalde commented on benchmark.py
> +                        "option reslim=3600;option threads=1;option optcr=1e-2;"
Blocking: The transformed-model path ignores the `timelimit` argument and always passes `option reslim=3600` to GAMS. A caller asking for a shorter or longer benchmark limit gets behavior different from the function signature, and the generated results become harder to reproduce. Build the GAMS `reslim` option from `timelimit` and keep non-GAMS solvers using their native time-limit option instead of hard-coding 3600.

2026-05-08 16:51 UTC, bernalde commented on benchmark.py
>          json.dump(results.json_repn(), f)
Blocking: This writes Python non-finite float tokens by default, and this PR already commits `.json` files containing `NaN`, `Infinity`, and `-Infinity`. Those tokens are not valid JSON, so strict parsers reject files such as `gdplib/syngas/benchmark_result/summary/gdpopt.enumerate_gams_baron.json`. Normalize non-finite bounds before writing, for example to `null` plus an explanatory status field or to strings, and call `json.dump(..., allow_nan=False)` so future runs cannot create invalid JSON artifacts.

2026-05-08 16:51 UTC, bernalde commented on benchmark.py
> +                # results.solver.strategy = strategy
Nonblocking: The GDPopt path still does not write the strategy or subsolver metadata into the JSON body; only the filename indicates that this was GAMS/BARON, and nothing records the NLP, MIP, MINLP, local MINLP roles or the solver options used. Consider adding a metadata block before dumping with strategy, solver interface, GAMS subsolver, each GDPopt subsolver role, options, and relevant Pyomo/GAMS versions so the stored summaries are self-describing.

2026-05-08 16:51 UTC, bernalde commented on benchmark.py
> +                except:
Blocking: This bare `except` silently drops every solver, import, transformation, or serialization failure. For benchmarking, that produces an apparently successful run with missing result files, which is hard to distinguish from intentionally skipped cases. Catch `Exception as err`, record the instance, strategy, solver, and traceback in a failure artifact or log, then return a nonzero status or re-raise after the batch so failures are visible.

2026-05-08 16:51 UTC, bernalde commented on generate_benchmark_summary_all.py
> +import plotly.graph_objects as go
Blocking: `plotly` is imported unconditionally but is not declared in `requirements.txt` or the current project dependencies, and this file does not use `go`. In this checkout, `python generate_benchmark_summary_all.py` fails at import time before reading any results. Remove the unused import, or add and document the dependency if plotting becomes part of this script.

2026-05-08 16:51 UTC, bernalde requested changes
Requesting changes. Blocking issues include the current merge conflict in benchmark.py, tracking generated benchmark_result artifacts, a hard-coded GAMS time limit, invalid non-standard JSON values in committed result files, hidden benchmark failures, and a summary script that fails because plotly is undeclared. Tests run: pixi run test could not run because this PR head has no pixi.toml or pyproject.toml; pytest tests/ could not run because this PR head has no tests/ directory; black --check --diff . fails on the outdated branch; black and flake8 on the changed scripts pass; compileall on the changed scripts passes; generate_benchmark_summary_all.py fails with ModuleNotFoundError: plotly; strict JSON validation fails on NaN/Infinity values. I would not merge this until the blocking issues are addressed.

2026-05-08 17:05 UTC, bernalde commented
Pushed:
- af55b28 Address benchmark review comments
- 8ceff30 Merge remote-tracking branch `origin/main` into `benchmark_zd`

Main changes:
- Removed generated `gdplib/*/benchmark_result` files from version control and restored the `benchmark_result` ignore rule. Added `benchmark_summary/` to `.gitignore`.
- Updated `benchmark.py` to use the requested `timelimit` for GAMS `reslim`, keep non-GAMS transformation solves on their native `timelimit` option, write strict JSON with non-finite values normalized to `null`, include benchmark metadata with GAMS/GDPopt subsolver roles, and record benchmark failures in failure logs before exiting nonzero.
- Removed the unused undeclared Plotly import from `generate_benchmark_summary_all.py`.
- Added `tests/test_benchmark.py` for timelimit handling, subsolver metadata, strict JSON normalization, and failure-log context.
- Merged current main into the PR branch and resolved the `benchmark.py` conflict; GitHub now reports the PR as mergeable.

Tests:
- `pixi run python -m pytest tests/test_benchmark.py -v --tb=short`: 6 passed.
- `pixi run test`: 250 passed.
- `pixi run lint`: passed. The advisory flake8 `--exit-zero` phase still reports existing style warnings, but the task exits 0.
- `pixi run python generate_benchmark_summary_all.py`: passed.
- Strict JSON validation over tracked `*.json` files with parse-constant rejection: passed.
- An initial concurrent `pixi run test` attempt failed with a transient `Text file busy` error while another Pixi command was linking the same environment; rerun serially passed.

Not addressed:
- I did not change model formulations or attempt the benchmark/model failure TODO list in the older discussion, including biofuel issue #62, because the actionable review threads were about benchmark infrastructure and result artifacts rather than model correctness. No model-failure issue needed an update from this pass.
- I left the choice to run SCIP-through-GAMS as a future benchmark run; `benchmark.py` now records the chosen GAMS subsolver metadata and still defaults this PR path to BARON.

Remaining risks/follow-up:
- `benchmark.py` still defaults the `__main__` list to a narrow manual run; broader benchmark campaigns should be run deliberately outside default tests because GAMS/BARON are optional external solvers.
- Existing advisory flake8 output remains outside the touched benchmark files.

2026-05-08 17:05 UTC, bernalde commented on benchmark.py
> +                        "option reslim=3600;option threads=1;option optcr=1e-2;"
Addressed in https://github.com/SECQUOIA/gdplib/commit/af55b28. benchmark.py now builds GAMS reslim from the timelimit argument, uses native timelimit for non-GAMS transformation solves, and tests cover both paths in tests/test_benchmark.py.

2026-05-08 17:05 UTC, bernalde commented on benchmark.py
> +                # results.solver.strategy = strategy
Addressed in https://github.com/SECQUOIA/gdplib/commit/af55b28. Result JSON now gets a Benchmark metadata block with strategy, time limit, solver interface, GAMS solver, and GDPopt subsolver roles; tests cover the GDPopt/GAMS metadata.

2026-05-08 17:05 UTC, bernalde commented on benchmark.py
>          json.dump(results.json_repn(), f)
Addressed in https://github.com/SECQUOIA/gdplib/commit/af55b28. benchmark.py now normalizes non-finite values before writing and uses json.dump(..., allow_nan=False); the generated result JSON artifacts were removed from the PR. Added test coverage and strict tracked-JSON validation passes.

2026-05-08 17:05 UTC, bernalde commented on benchmark.py
> +                except:
Addressed in https://github.com/SECQUOIA/gdplib/commit/af55b28. The batch runner now catches Exception as err, writes a failure log with instance/strategy/solver/traceback, records failures, and exits nonzero after the batch.

2026-05-08 17:05 UTC, bernalde commented on generate_benchmark_summary_all.py
> +import plotly.graph_objects as go
Addressed in https://github.com/SECQUOIA/gdplib/commit/af55b28. Removed the unused Plotly import; pixi run python generate_benchmark_summary_all.py now runs successfully.

2026-05-08 17:05 UTC, bernalde commented on .gitignore
> +gdplib/*/benchmark_result/*.log
Addressed in https://github.com/SECQUOIA/gdplib/commit/af55b28. I removed the generated benchmark_result files from version control, restored gdplib/*/benchmark_result/ in .gitignore, and added benchmark_summary/ for generated summary output.

2026-05-10 13:54 UTC, bernalde commented
Wrap-up status for PR #58:

- This is now best treated as a benchmark infrastructure PR. I did not add generated benchmark outputs to the branch; outputs remain ignored under `gdplib/*/benchmark_result/`, `benchmark_runs/`, and `benchmark_summary/`.
- Current CI is green on head `b951665`.
- The reusable benchmark CLI and case-file path are in place: `gdplib-benchmark preflight`, `gdplib-benchmark run`, and `gdplib-benchmark warnings`. The tracked `benchmark_cases/pr58_local.csv` provides the full 1-hour local matrix, and targeted instance runs can use `--instances`, `--strategies`, `--solver-profile`, and `--timelimit`.
- 5-minute Big-M smoke evidence was collected and recorded in issues instead of committed as generated artifacts: central summary #60, deprecation candidates #55, and per-instance records #61-#77.

Notable follow-up from the smoke run:

- Direct transformed pure-MIP cases should use Gurobi or another MIP solver rather than DICOPT. The local DICOPT profile failed for `disease_model` and `med_term_purchasing` with `GAMS writer passed solver (dicopt) unsuitable for model type (mip)`.
- Deprecation candidates are concentrated in `gdp_col`, `med_term_purchasing`, and `small_batch`; details are in #55.
- BARON completed all 17 Big-M smoke cases at the runner level, but `hda` and `stranded_gas` reported infeasible and `kaibel` hit `maxTimeLimit`; details are in the model issues.

Recommended review focus: CLI/API behavior, case-file schema, solver-profile defaults and overrides, generated-output isolation, strict JSON/failure metadata, and warning capture. Enough changed since the original review to justify a fresh review round.

2026-05-10 13:58 UTC, bernalde approved these changes

2026-05-10 13:58 UTC, merged