Add water_network instance
SECQUOIA/gdplib pull request #59
Opened 2024-09-03 19:52 UTC by tristantc

This pull request incorporates the `water_network` instance.
Please review the changes and provide feedback. Thank you!

2024-09-10 00:08 UTC, ZedongPeng commented
Hi @tristantc . The linter check failed. 
- I think the `m.gam` has already been fixed in the `main` branch. You need to merge the `main` branch and resolve the conflicts. 
- The other one is `m.ue`. I am not sure if it is a good name. If you want to use `m.ue`, you need to add `ue` to https://github.com/SECQUOIA/gdplib/blob/main/.github/workflows/typos.toml

2024-09-10 00:42 UTC, tristantc commented
Thanks for the feedback, @ZedongPeng.
I will stick with `ue` for now, but I am willing to switch it if there is a better way to name it.

2024-09-10 01:13 UTC, ZedongPeng requested changes

2024-09-10 01:13 UTC, ZedongPeng commented on gdplib/README.md
> +| `water_network` |      |      |     |     |      |      |    |      |        |
These numbers need to be updated.

2024-09-10 01:13 UTC, ZedongPeng commented on gdplib/README.md
> +## Water Network Design
The `README.md` file should be moved to the `water_network` folder.

2024-09-10 01:13 UTC, ZedongPeng commented on gdplib/water_network/T.csv
> +cont,T
The `CSV` file looks small. Maybe instead of creating the `CSV` file, we should define a dictionary in the Python script. This also applies to `TU.csv` and `feed.csv`.

2024-09-10 01:13 UTC, ZedongPeng commented on gdplib/water_network/wnd.py
> +# import pyomo.gdp as gdp
Remove the unused import.

2024-09-10 01:13 UTC, ZedongPeng commented on gdplib/water_network/wnd.py
> +import os
It might be better to move all `import` before variable definition, like 'ureg = UnitRegistry()'

2024-09-10 01:13 UTC, ZedongPeng commented on gdplib/water_network/wnd.py
> +        ],  # pyo.RangeSet(m.nr)]
Remove commented code.

2024-09-10 01:13 UTC, ZedongPeng commented on gdplib/README.md
> +The instance incorporates two approximations of the concave cost term (piecewise linear and quadratic) to reformulate the GDP model into a bilinear quadratic one.
We might need to introduce how to build these two formulations by giving an example as follows.

- `build_model(approximation='quadratic')`
- `build_model(approximation='piecewise')`

2024-09-10 01:19 UTC, tristantc commented on gdplib/README.md
> +## Water Network Design
Thank you for pointing out the mistake

2024-09-10 01:22 UTC, tristantc commented on gdplib/water_network/wnd.py
> +# import pyomo.gdp as gdp
Thank you, I deleted the unused import

2024-09-10 01:24 UTC, tristantc commented on gdplib/water_network/wnd.py
> +import os
Rearranged the code to have imports come before variable assignment

2024-09-10 01:47 UTC, tristantc commented on gdplib/water_network/wnd.py
> +        ],  # pyo.RangeSet(m.nr)]
I deleted some commented-out code and kept the ones that set the maximum flowrate to match Ruiz and Grossmann (2009).

2024-09-10 14:11 UTC, bernalde requested changes
Good addition. Now, does it run with the benchmark code?

2024-09-10 14:11 UTC, bernalde commented on .github/workflows/typos.toml
> +ue = "ue"
What is ue?

2024-09-10 14:11 UTC, bernalde commented on gdplib/water_network/README.md
> +| Component             | pwl | quadratic |
What about the original one?

2024-09-10 14:11 UTC, bernalde commented on gdplib/water_network/T.csv
> +cont,T
We would like to scale this instance to more cases, so I rather leave all in CSVs

2024-09-10 14:11 UTC, bernalde commented on gdplib/water_network/wnd.py
> +        ue = m.unit_exists[unit]
Why add this uninformative variable name instead of just spending some terms as unit_exists?

2024-09-10 14:11 UTC, bernalde commented on gdplib/water_network/wnd.py
> +            # bounds=lambda _, j, i, k: (feed[j].min(),100) if i==unit else (feed[j].min(),4)
Why are these comments here? Do we need them?

2024-09-10 14:54 UTC, tristantc commented on gdplib/water_network/wnd.py
> +        ue = m.unit_exists[unit]
To make it less verbose

2024-09-10 14:57 UTC, tristantc commented on gdplib/water_network/wnd.py
> +        ue = m.unit_exists[unit]
If you think it is better, I can switch `ue` to `unit_exists`

2024-09-10 15:01 UTC, tristantc commented on gdplib/water_network/wnd.py
> +            # bounds=lambda _, j, i, k: (feed[j].min(),100) if i==unit else (feed[j].min(),4)
I kept them in case we need a lower bound on concentration, not zero.

2024-09-10 15:01 UTC, tristantc commented on .github/workflows/typos.toml
> +ue = "ue"
`ue` stands for `unit_exists`

2024-09-10 15:09 UTC, tristantc commented on gdplib/water_network/README.md
> +| Component             | pwl | quadratic |
Chose not to upload the MINLP model because it's not a GDP model, but a GAMS model transformed into pyomo or are you asking about the model size table?

2024-09-16 15:20 UTC, tristantc commented on gdplib/water_network/wnd.py
> +        elif approximation == "piecewise":
`quadratic2` function fits original function better than `quadratic`, but not zero at zero flowrate.
Best known objective: $348,340
`quadratic` $346,672
`quadratic2` $349,555

2024-09-16 15:57 UTC, tristantc commented on gdplib/water_network/README.md
> +| Component             | pwl | quadratic |
I incorporated the original model without any approximation.

2024-09-16 16:24 UTC, tristantc commented
> Good addition. Now, does it run with the benchmark code?

BigM and Hull MINLP reformulations work.
Neither the logic-based methods nor enumeration yield the optimal solution.

2024-10-10 16:00 UTC, bernalde commented on gdplib/water_network/wnd.py
> +        ue = m.unit_exists[unit]
Yes

2024-10-10 16:01 UTC, bernalde commented on gdplib/water_network/wnd.py
> +            # bounds=lambda _, j, i, k: (feed[j].min(),100) if i==unit else (feed[j].min(),4)
A nonzero bound is unphysical, delete the comment

2024-10-10 16:02 UTC, bernalde commented on gdplib/water_network/wnd.py
> +        elif approximation == "piecewise":
Either in the documentation or in the README explain what quadratic and quadratic2 are. I would recommend to rename the models to quadratic_zero_origin and quadratic_nonzero_origin

2024-10-10 16:05 UTC, bernalde requested changes
There are a few open comments to be addressed and then we can merge this

2024-10-10 16:05 UTC, bernalde commented on gdplib/water_network/wnd.py
> +            # bounds=lambda _,i,k:(TU.loc[unit,'L'],100) # Upper bound for the flow rate from Ruiz and Grossmann (2009) is 100
Why not adding the same bound as the original instance?

2024-10-10 22:59 UTC, bernalde approved these changes

2024-10-11 22:17 UTC, ZedongPeng commented on gdplib/water_network/wnd.py
> +        [
It might be better and clearer to use a normal `for` loop here, instead of implicitly creating a `list`.

2024-10-11 22:17 UTC, ZedongPeng commented on gdplib/water_network/wnd.py
> +    # init_vars.InitMidpoint().apply_to(m)
Do we need to add an argument for the initialization? Or just remove it?

2024-10-11 22:17 UTC, ZedongPeng commented on gdplib/water_network/wnd.py
> +wnd_dir = os.path.dirname(os.path.realpath(__file__))
What will happen if we remove this line? Just curious.

2024-10-15 16:32 UTC, tristantc commented on gdplib/water_network/wnd.py
> +        elif approximation == "piecewise":
Does it make sense to hold onto both versions?

2024-10-15 16:32 UTC, tristantc commented on gdplib/water_network/wnd.py
> +            # bounds=lambda _,i,k:(TU.loc[unit,'L'],100) # Upper bound for the flow rate from Ruiz and Grossmann (2009) is 100
The overall feed flow rate is less than 100.
It provides increased flexibility for multiple cases.

2024-10-15 16:32 UTC, tristantc commented on gdplib/water_network/wnd.py
> +    # init_vars.InitMidpoint().apply_to(m)
I opted not to use it, saving it in case of uninitialized variables.
I can remove the comment.

2024-10-15 16:32 UTC, tristantc commented on gdplib/water_network/wnd.py
> +        [
I can use a regular for loop instead of a list comprehension if you consider it worthwhile.

2024-10-15 16:32 UTC, tristantc commented on gdplib/water_network/wnd.py
> +wnd_dir = os.path.dirname(os.path.realpath(__file__))
It's a concise way for specifying the directory of `CSV` data files.
Is there a different way to handle this?

2024-10-15 16:33 UTC, bernalde commented on gdplib/water_network/wnd.py
> +        [
I agree with Carolina, we can leave this as is

2024-10-15 16:33 UTC, bernalde commented on gdplib/water_network/wnd.py
> +wnd_dir = os.path.dirname(os.path.realpath(__file__))
Although the current file path is included by default, there is not an issue in being verbose here in case someone wants to use a different path for the files.

2024-10-15 16:34 UTC, bernalde commented on gdplib/water_network/wnd.py
> +    # init_vars.InitMidpoint().apply_to(m)
I would leave the comment, I didn't know one could do this, but I would also add an extra comment before explaining what this line does

2024-10-15 16:39 UTC, ZedongPeng approved these changes

2024-11-04 13:10 UTC, tristantc commented on gdplib/water_network/wnd.py
> +    # init_vars.InitMidpoint().apply_to(m)
I added an annotation to make the code clearer.

2024-11-04 13:12 UTC, merged