add citation
SECQUOIA/gdplib pull request #7
Opened 2023-09-14 17:54 UTC by ZedongPeng

2023-09-15 02:23 UTC, bernalde commented
Use this citation file instead:
`@incollection{bernal2022advances,
  title={Advances in Generalized Disjunctive and Mixed-Integer Nonlinear Programming Algorithms and Software for Superstructure Optimization},
  author={Bernal, David E and Liu, Yunshan and Bynum, Michael L and Laird, Carl D and Siirola, John D and Grossmann, Ignacio E},
  booktitle={Computer Aided Chemical Engineering},
  volume={49},
  pages={1285--1290},
  year={2022},
  publisher={Elsevier}
}`

2023-09-19 18:54 UTC, ZedongPeng commented
@bernalde

2023-09-19 19:04 UTC, bernalde requested changes

2023-09-19 19:04 UTC, bernalde commented on CITATION.ccf
> +  - family-names: Liu
Add yourself @ZedongPeng and add my second last name. Also search if the other authors have orcid.

2023-09-19 21:00 UTC, ZedongPeng commented on CITATION.ccf
> +  - family-names: Liu
done.

2023-09-19 23:06 UTC, bernalde approved these changes

2023-09-19 23:06 UTC, merged