Add Reverse Electrodialysis model
SECQUOIA/gdplib pull request #78
Opened 2024-12-09 23:36 UTC by tristantc

Introduce a new GDP model for the optimal design of the reverse electrodialysis process, including relevant data and documentation.

2024-12-10 19:53 UTC, bernalde requested changes
I haven't reviewed the REDstack.py file but I suppose that many of the comments for the other python file apply, so let's cover those for both files first, and then I will complete the review.
In general, there are a few typos, many "magic number" (numbers in the constraints that should be defined as parameters) and several comments that should be either removed or integrated as notes or documentation of the Pyomo model elements.
Another big one is that I want you to replace the Excel file with CSV files and sort out the imports

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +- Maximize the net present value (NPV) of the RED process.
Dollar units missing [$]

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +
This can be organized using a 'sort import' command

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +from pyomo.core.expr.logical_expr import *
Importing things as * is not good practice. Have the methods explicitly imported

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +# The data.xlsx file contains the financial and stack parameters, and properties of the high and low salinity feed streams.
Can you import this from CSV files instead of Excel? These are harder to read in Unix.

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        return re.findall(r'\d+', x) == re.findall(r'\d+', y)
Can you explain this regular expression line?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +    )  # Filter function _from_splitters_filter as suggested in Pyomo PR #3338 (Support validate / filter for IndexedSet components using the index) that fixes the issue #2655
Mention this PR in that Pyomo issue/PR. Same with any other reference in the code

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            cst = 2 * m.gas_constant * m.T / m.faraday_constant * m.iems_permsel_avg
You need a better name for this variable

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +    m.faraday_constant = cst.physical_constants['Faraday constant'][
If you are importing scipy.cst from only defining these two constants, it is better to define them yourself. Importing the whole scipy for this is unnecessarily bloating the dependencies

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        # initialize = 0.07, # 0.07–0.12 (EIA) US 2019 annual average prices industrial costumers
Complete reference

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        doc="Elctricity price [USD kWh-1]",
typo

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +    # initialize=1.)
Remove comments that are not necessary

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +                #                 if flow_init * m.nr > feed_flow_vol['fl1']:
Do we still need these comments?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        # lb = pyo.value(36 * m.vel_lb[sol] * m._cross_area[sol] * m.cell_pairs)
Why is this commented out?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        ub = pyo.value(36 * m.vel_ub[sol] * m._cross_area[sol] * m.cell_pairs)
Where is magic number 36 coming from?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        initialize=lambda m: m_stack.GP.value * 1e-2,
Where are the 1e-2 magic numbers coming from?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        return m.iems_cap_cost * (1 + 0.517)  # 51.7% IEMs cap. cost
Create a parameter for this

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            ureg.convert(48e-7 * m.vel_init[sol] / m.dh[sol] ** 2 * m.L, 'mbar', 'Pa')
Where is this 48e-7 coming from?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            + m.electricity_price * 8760 * m.load_factor * ureg.convert(PP, 'W', 'kW')
8760 is a magic number

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            flow_init = pyo.value(36 * m.vel_init[sol] * m._cross_area[sol])
36?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        #             return (feed_conc_mol['fl1'], m.conc_mol_eq.ub)
Unnecessary comment

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +                48
48?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            # lb = ub - ureg.convert(delta_p, 'Pa', 'mbar')
Why removing this lower bound?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            #                                initialize=101325.0,
Remove

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +                2e3
Where is this factor coming from?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +                ub = 7.7228559 * flow_conc_data['feed_conc_mol']['fh1'] + 0.5670209
Where do these correlations come from?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            ),  # 0.02 is the temperature coefficient of the conductivity from the literature
Which datapoint in the literature? Create a parameter for this

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +                    * 1e4
More magic numbers

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            bounds=(0.2, 100.0),  # (0.02,100.),
Where are these coming from?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        #         ru.Rload.fix(8.75)
I guess we don't know this anymore

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            initialize=lambda _: _int_trap_rule(ru.length_domain, ru.Idx) * m.Aiem * 10,
Where is this 10 coming from?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            lb = ru.Idx[0].lb * 3.6e4 / m.faraday_constant
More magic numbers (3.6e4)

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +                    -48
Magic number

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +                    48e-7 * m.vel_init[sol] / m.dh[sol] ** 2 * m.L, 'mbar', 'Pa'
Magic number

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        def _nernst_potential_cp(ru, x):  # Rg[J mol-1 K-1] , F[A s mol-1], T[K]
All the units should go in the function documentation, either in arguments or returns

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +                == m.spacer_thickness[sol] / m.spacer_porosity[sol] ** 2 * 1e4
More magic numbers (1e4)

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        #             return ru.Jcond[x] * m.faraday_constant == ru.Idx[x] * 3.6e4 # J [mol m-2 h-1], F [A s mol-1], Id[mA cm-2]
These units should be put in the function or documentation

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            # dC/dx [mol L-1 m-1] * [m3 h-1] * 1e3 [L m-3] = [m] [mol m-2 h-1]
This is great for notes in the documentation

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            # [mbar m-1]; 1e-2 [mbar Pa-1]; mu = 1 cP = 1e-3 Pa s; v [cm s-1] * m/100cm;
This should go in the documentation

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            lb = pyo.value(36 * m.vel_lb[sol] * m._cross_area[sol] * m.cell_pairs)
Magic number

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            # [USD] Stack + electrodes = 51.7% IEMs
Add the number as a parametr with corresponding documentation and correct citation

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +    # New var. for pump capital cost: Z = sum(Q)**0.9, Z >= 0
This is precisely what should go in the variable documentation

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            sum(6900 + 206 * m.pump_cap_cost_var[sol] for sol in m.SOL)
These magic numbers should be parameters

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +            + m.TNP * 250 * m.eur2usd  # Civil and infrastructure costs [USD kW-1]
Why 250?

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        )  # O&M = 2%–4% CAPEX [USD y-1]
Add parameter with documentation with complete reference

2024-12-10 19:53 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        # Assuming energy produced w selling price eq ep [USD]
Why complete sentence as a note to the documentation

2024-12-16 16:55 UTC, tristantc commented on gdplib/reverse_electrodialysis/REDprocess.py
> +        # lb = pyo.value(36 * m.vel_lb[sol] * m._cross_area[sol] * m.cell_pairs)
The lower bound applies to the active RED unit based on the minimum linear velocity in both the HC and LC channels.

2024-12-16 17:11 UTC, tristantc commented on gdplib/reverse_electrodialysis/REDprocess.py
> +    m.faraday_constant = cst.physical_constants['Faraday constant'][
I opted to import just the `physical_constants` dictionary from the `scipy.constants` module rather than the entire `scipy` package.

2024-12-16 17:35 UTC, tristantc commented on gdplib/reverse_electrodialysis/REDprocess.py
> +# The data.xlsx file contains the financial and stack parameters, and properties of the high and low salinity feed streams.
I tried to load data from CSVs but ran into an `AttributeError`, so I need to work on a solution.
Commented out in commit e2259c6f7a688d17eb2c7a0d85d8e1fd02c90e81

2025-07-01 20:29 UTC, bernalde requested changes
We are very close for this to be merged! Besides the small comment regarding unit formatting, this needs a README presenting the model, some simple stats and references.

2025-07-01 20:29 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +    # Ideal gas constant [J mol-1 K-1]
I think this notation can be confusing with several units in the denominator or powers. I rather be explicit about the powers and the stuff in the denominator. J/mol/K or J/(mol*K)

2025-07-01 20:29 UTC, bernalde commented on gdplib/reverse_electrodialysis/REDprocess.py
> +                ureg.convert(m.vel_init[sol], 'cm/s', 'm/h')
This will solve our unit's issues! Let's follow the notation here!

2025-07-04 15:51 UTC, tristantc commented on gdplib/reverse_electrodialysis/REDprocess.py
> +    )  # Filter function _from_splitters_filter as suggested in Pyomo PR #3338 (Support validate / filter for IndexedSet components using the index) that fixes the issue #2655
Mentioned in https://github.com/SECQUOIA/gdplib/issues/79

2025-07-04 16:22 UTC, tristantc commented on gdplib/reverse_electrodialysis/REDprocess.py
> +    # Ideal gas constant [J mol-1 K-1]
Units notation updated in cae17a5e6f403663fac83337195ecfbc0274d8ad and https://github.com/SECQUOIA/gdplib/pull/78/commits/2e9d2331b9763fb723b803c54f530a2fb1e83c6c

2025-07-08 00:15 UTC, bernalde requested changes
The files are ready but this is still missing the README file for the model with a report on its size, reference, and optimal solution.

2025-07-08 01:35 UTC, tristantc commented
> The files are ready but this is still missing the README file for the model with a report on its size, reference, and optimal solution.

I added the `README.md` file in commit de6d633bbce3d82253a15333cbf9cd2d24a85498

2025-07-22 06:33 UTC, bernalde approved these changes

2025-07-22 06:34 UTC, merged