Added Documentation for pyomo examples (batch_processing.py)
SECQUOIA/gdplib pull request #9
Opened 2023-11-02 15:57 UTC by AlbertLee125

I added the documentation for the batch_processing.py.

2023-11-02 15:58 UTC, AlbertLee125 commented
From the TODO list, I can assume the code is formulated based on the existing GAMS studio code. I will remove the TODO and then rewrite the documentation.

2023-11-03 04:29 UTC, bernalde requested changes

2023-11-03 04:29 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      StorageTankSizeFactor = 2*5 # btw, I know 2*5 is 10... I don't know why it's written this way in GAMS?
Myabe you can remove this comment and just write 10

2023-11-03 04:29 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      # TODO: YOU ARE HERE. YOU HAVEN'T ACTUALLY MADE THESE THE BOUNDS YET, NOR HAVE YOU FIGURED OUT WHOSE
Is this TODO still required?

2023-11-03 04:29 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      # TODO: these aren't in the formulation??
Can you review this?

2023-11-03 04:29 UTC, bernalde commented
Do it

2023-11-16 00:14 UTC, bernalde requested changes
Please address the comments before resolving the conversations

2023-11-16 00:14 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      StorageTankSizeFactor = 2*5 # btw, I know 2*5 is 10... I don't know why it's written this way in GAMS?
You resolved the comments without addressing it. Please work on it and commit it before resolving the comments

2023-11-16 00:14 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      # TODO: YOU ARE HERE. YOU HAVEN'T ACTUALLY MADE THESE THE BOUNDS YET, NOR HAVE YOU FIGURED OUT WHOSE
Same as above

2023-11-16 00:14 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      # TODO: these aren't in the formulation??
Same as above

2023-11-16 00:14 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>          return model.volume_log[j] >= log(model.ProductSizeFactor[i, j]) + model.batchSize_log[i, j] - \
Function documentation missing

2023-11-16 00:14 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      def storage_tank_selection_disjunct_rule(disjunct, selectStorageTank, j):
Function documentation missing

2024-04-04 22:50 UTC, bernalde requested changes
Do not do commits with intermediate states unless you are working on "work in progress" PRs [WIP]

2024-04-04 22:50 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
> +    """_summary_
Please do not commit this kind of changes. Commits should have more meaningful states

2024-04-05 14:09 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
>      # TODO: YOU ARE HERE. YOU HAVEN'T ACTUALLY MADE THESE THE BOUNDS YET, NOR HAVE YOU FIGURED OUT WHOSE
I think I will just leave it as it was.

2024-04-10 01:25 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
> +    """_summary_
I added the documentation for each function definition.

2024-04-10 01:25 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
>      def storage_tank_selection_disjunct_rule(disjunct, selectStorageTank, j):
Added the Documentation of the functions.

2024-04-10 01:26 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
>          return model.volume_log[j] >= log(model.ProductSizeFactor[i, j]) + model.batchSize_log[i, j] - \
Added Function documentation.

2024-04-10 01:40 UTC, bernalde requested changes
This file still needs work. @tristantc please aid Albert in it. You might need to go back to the GAMS implementation described here https://www.minlplib.org/batchs101006m.html and found here http://egon.cheme.cmu.edu/ibm/page.htm and here https://minlp.org/library/problem/index.php?i=172&lib=GDP

2024-04-10 01:40 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
> +# Problem from http://www.minlp.org/library/problem/index.php?i=172&lib=GDP
The other codes had a header from Pyomo. Please include that here

2024-04-10 01:40 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
> +    Ravemark, E. Optimization models for design and operation of chemical batch processes. Ph.D. Thesis, ETH Zurich, 1995.
DOI missing

2024-04-10 01:40 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
> +    StorageTankSizeFactor = 10
Do you have any details on the units or a more detailed description of these?

2024-04-10 01:40 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      model.storageTankSizeLB = Param(model.STAGES, default=StorageTankSizeLB)
Missing docs

2024-04-10 01:40 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      model.volume_log = Var(model.STAGES, bounds=get_volume_bounds)
Missing docs

2024-04-10 01:40 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      model.unitsInPhase_log = Var(model.STAGES, bounds=get_unitsInPhase_bounds)
Missing docs

2024-04-10 01:40 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      # though this is a disjunction in the GAMs model, it is more efficiently formulated this way:
What does this comment refer to?

2024-04-10 01:40 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      # and since I didn't do the disjunction as a disjunction, we need the XORs:
This comment is no longer relevant

2024-04-10 01:41 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
>      # TODO: these aren't in the formulation??
The one written in the TODO list. 
https://www.minlp.org/library/problem/index.php?i=172&lib=GDP I checked the Nomenclature of the Design of the Multi-product Batch Plant. There are no sets for the storage tanks.

2024-04-10 01:43 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
>      # and since I didn't do the disjunction as a disjunction, we need the XORs:
I will remove the comments.

2024-04-10 01:46 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
> +# Problem from http://www.minlp.org/library/problem/index.php?i=172&lib=GDP
Added the header.

2024-04-10 02:03 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
> +    StorageTankSizeFactor = 10
Unfortunately, I do not know the units. https://www.minlp.org/problems/mod/229/GDP_model.pdf According to this website. They only show the nomenclature not the detail unit.

2024-04-10 02:10 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
> +    StorageTankSizeFactor = 10
Not there, but go deeper. Check Ravemach thesis

2024-04-10 02:17 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
> +    StorageTankSizeFactor = 10
https://www.research-collection.ethz.ch/handle/20.500.11850/142491
I cannot get the access for the Full text.

2024-04-10 02:21 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
> +    StorageTankSizeFactor = 10
Here is the DOI of his. https://doi.org/10.3929/ethz-a-001591449
I can only get the access of the Abstract. Is there any way to get approval?

2024-04-17 01:50 UTC, bernalde requested changes
Some comments are still open.
We should also start adding the description of the files in the README in a next PR

2024-04-17 01:50 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      # TODO: these bounds make it infeasible...
Does this mean this function is not used? If not, please add more context to the comment

2024-04-17 01:50 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      # though this is a disjunction in the GAMs model, it is more efficiently formulated this way:
@AlbertLee125 @tristantc @ZedongPeng

2024-04-23 18:24 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
> +    Ravemark, E. Optimization models for design and operation of chemical batch processes. Ph.D. Thesis, ETH Zurich, 1995.
Added the DOI

2024-04-23 19:28 UTC, AlbertLee125 commented on gdplib/pyomo_examples/batch_processing.py
>      # TODO: these bounds make it infeasible...
I think what the TODO: was talking about setting the bound, or hard coding the boundary can make the boundary infeasible. Shall I erase it?

2024-04-23 19:40 UTC, bernalde commented on gdplib/pyomo_examples/batch_processing.py
>      # TODO: bonmin wasn't happy and I think it might have something to do with this?
This is an interesting comment. I will not keep this PR open but we should take this into account.

2024-04-23 19:40 UTC, bernalde approved these changes

2024-04-27 20:57 UTC, merged